/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 4
#define BCM_REL_RELEASE 13
#define BCM_REL_PATCH 1
#define BCM_SW_VERSIONCODE (4*65536+13*256+1)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
