/***************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on              Thu Sep  4 04:51:45 2014
 *                 Full Compile MD5 Checksum 8b9bd5137765e5dce9d70a0afe4b52c1
 *                   (minus title and desc)
 *                 MD5 Checksum              806e214b76041b03796d46a801f2d917
 *
 * Compiled with:  RDB Utility               combo_header.pl
 *                 RDB Parser                3.0
 *                 unknown                   unknown
 *                 Perl Interpreter          5.008008
 *                 Operating System          linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_TOKEN_GFAP_H__
#define BCHP_TOKEN_GFAP_H__

/***************************************************************************
 *Token_GFAP
 ***************************************************************************/
#define BCHP_Token_GFAP_TOK_BUF_SIZE             0x13c01400 /* TOK BUF SIZE Register */
#define BCHP_Token_GFAP_TOK_BUF_BASE             0x13c01404 /* TOK BUF BASE Register */
#define BCHP_Token_GFAP_TOK_IDX2PTR_IDX          0x13c01408 /* TOK IDX2PTR IDX Register */
#define BCHP_Token_GFAP_TOK_IDX2PTR_PTR          0x13c0140c /* TOK IDX2PTR PTR Register */
#define BCHP_Token_GFAP_TOK_BUF_SIZE2            0x13c01418 /* TOK BUF SIZE 2 Register */

/***************************************************************************
 *TOK_BUF_SIZE - TOK BUF SIZE Register
 ***************************************************************************/
/* Token_GFAP :: TOK_BUF_SIZE :: reserved0 [31:08] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE_reserved0_MASK                0xffffff00
#define BCHP_Token_GFAP_TOK_BUF_SIZE_reserved0_SHIFT               8

/* Token_GFAP :: TOK_BUF_SIZE :: POOL_3_SIZE [07:06] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_3_SIZE_MASK              0x000000c0
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_3_SIZE_SHIFT             6
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_3_SIZE_DEFAULT           0x00000000

/* Token_GFAP :: TOK_BUF_SIZE :: POOL_2_SIZE [05:04] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_2_SIZE_MASK              0x00000030
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_2_SIZE_SHIFT             4
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_2_SIZE_DEFAULT           0x00000000

/* Token_GFAP :: TOK_BUF_SIZE :: POOL_1_SIZE [03:02] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_1_SIZE_MASK              0x0000000c
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_1_SIZE_SHIFT             2
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_1_SIZE_DEFAULT           0x00000000

/* Token_GFAP :: TOK_BUF_SIZE :: POOL_0_SIZE [01:00] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_0_SIZE_MASK              0x00000003
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_0_SIZE_SHIFT             0
#define BCHP_Token_GFAP_TOK_BUF_SIZE_POOL_0_SIZE_DEFAULT           0x00000000

/***************************************************************************
 *TOK_BUF_BASE - TOK BUF BASE Register
 ***************************************************************************/
/* Token_GFAP :: TOK_BUF_BASE :: BASE [31:00] */
#define BCHP_Token_GFAP_TOK_BUF_BASE_BASE_MASK                     0xffffffff
#define BCHP_Token_GFAP_TOK_BUF_BASE_BASE_SHIFT                    0
#define BCHP_Token_GFAP_TOK_BUF_BASE_BASE_DEFAULT                  0x00000000

/***************************************************************************
 *TOK_IDX2PTR_IDX - TOK IDX2PTR IDX Register
 ***************************************************************************/
/* Token_GFAP :: TOK_IDX2PTR_IDX :: BUFR_IDX [31:00] */
#define BCHP_Token_GFAP_TOK_IDX2PTR_IDX_BUFR_IDX_MASK              0xffffffff
#define BCHP_Token_GFAP_TOK_IDX2PTR_IDX_BUFR_IDX_SHIFT             0
#define BCHP_Token_GFAP_TOK_IDX2PTR_IDX_BUFR_IDX_DEFAULT           0x00000000

/***************************************************************************
 *TOK_IDX2PTR_PTR - TOK IDX2PTR PTR Register
 ***************************************************************************/
/* Token_GFAP :: TOK_IDX2PTR_PTR :: RTN_BUFR_PTR [31:00] */
#define BCHP_Token_GFAP_TOK_IDX2PTR_PTR_RTN_BUFR_PTR_MASK          0xffffffff
#define BCHP_Token_GFAP_TOK_IDX2PTR_PTR_RTN_BUFR_PTR_SHIFT         0
#define BCHP_Token_GFAP_TOK_IDX2PTR_PTR_RTN_BUFR_PTR_DEFAULT       0x00000000

/***************************************************************************
 *TOK_BUF_SIZE2 - TOK BUF SIZE 2 Register
 ***************************************************************************/
/* Token_GFAP :: TOK_BUF_SIZE2 :: reserved0 [31:01] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE2_reserved0_MASK               0xfffffffe
#define BCHP_Token_GFAP_TOK_BUF_SIZE2_reserved0_SHIFT              1

/* Token_GFAP :: TOK_BUF_SIZE2 :: SIZE [00:00] */
#define BCHP_Token_GFAP_TOK_BUF_SIZE2_SIZE_MASK                    0x00000001
#define BCHP_Token_GFAP_TOK_BUF_SIZE2_SIZE_SHIFT                   0
#define BCHP_Token_GFAP_TOK_BUF_SIZE2_SIZE_DEFAULT                 0x00000000

#endif /* #ifndef BCHP_TOKEN_GFAP_H__ */

/* End of File */
