/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Mar  3 03:33:07 2015
 *                 Full Compile MD5 Checksum  b5f19c74ab37a2906e9421a8b2559715
 *                     (minus title and desc)
 *                 MD5 Checksum               778db12b311d8f0cfe2c790ec2a4bd84
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_MIB1_H__
#define BCHP_MIB1_H__

/***************************************************************************
 *MIB1 - MIB Registers
 ***************************************************************************/
#define BCHP_MIB1_GRFCS                          0x12c02c00 /* [RW] Receive FCS Error Counter */
#define BCHP_MIB1_GRXCF                          0x12c02c04 /* [RW] Receive Control Frame Packet Counter */
#define BCHP_MIB1_GRXPF                          0x12c02c08 /* [RW] Receive Pause Frame Packet Counter */
#define BCHP_MIB1_GRXUO                          0x12c02c0c /* [RW] Receive Unknown OP Code Packet Counter */
#define BCHP_MIB1_GRALN                          0x12c02c10 /* [RW] Receive Alignmenet Error Counter */
#define BCHP_MIB1_GRFLR                          0x12c02c14 /* [RW] Receive Frame Length Out Of Range Counter */
#define BCHP_MIB1_GRCDE                          0x12c02c18 /* [RW] Receive Code Error Packet Counter */
#define BCHP_MIB1_GRFCR                          0x12c02c1c /* [RW] Receive Carrier Sense Error Packet Counter */
#define BCHP_MIB1_GROVR                          0x12c02c20 /* [RW] Receive Oversize Packet Counter */
#define BCHP_MIB1_GRJBR                          0x12c02c24 /* [RW] Receive Jabber Counter */
#define BCHP_MIB1_GRMTUE                         0x12c02c28 /* [RW] Receive MTU Error Packet Counter */
#define BCHP_MIB1_RRPKT                          0x12c02c2c /* [RW] Receive RUNT Packet Counter */
#define BCHP_MIB1_RRUND                          0x12c02c30 /* [RW] Receive RUNT Packet And Contain A Valid FCS */
#define BCHP_MIB1_RRFRG                          0x12c02c34 /* [RW] Receive RUNT Packet And Contain Invalid FCS or Alignment Error */
#define BCHP_MIB1_RRBYT                          0x12c02c38 /* [RW] Receive RUNT Packet Byte Counter */
#define BCHP_MIB1_GRMCA                          0x12c02c3c /* [RW] Receive Multicast Frame Counter */
#define BCHP_MIB1_GRBCA                          0x12c02c40 /* [RW] Receive Broadcast Frame Counter */
#define BCHP_MIB1_GR64                           0x12c02c44 /* [RW] Receive 64B Frame Counter */
#define BCHP_MIB1_GR127                          0x12c02c48 /* [RW] Receive 65B to 127B Frame Counter */
#define BCHP_MIB1_GR255                          0x12c02c4c /* [RW] Receive 128B to 255B Frame Counter */
#define BCHP_MIB1_GR511                          0x12c02c50 /* [RW] Receive 256B to 511B Frame Counter */
#define BCHP_MIB1_GR1023                         0x12c02c54 /* [RW] Receive 512B to 1023B Frame Counter */
#define BCHP_MIB1_GR1518                         0x12c02c58 /* [RW] Receive 1024B to 1518B Frame Counter */
#define BCHP_MIB1_GRMGV                          0x12c02c5c /* [RW] Receive 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB1_GR2047                         0x12c02c60 /* [RW] Receive 1522B to 2047B Frame Counter */
#define BCHP_MIB1_GR4095                         0x12c02c64 /* [RW] Receive 2048B to 4095B Frame Counter */
#define BCHP_MIB1_GR9216                         0x12c02c68 /* [RW] Receive 4096B to 9216B Frame Counter */
#define BCHP_MIB1_GRPKT                          0x12c02c6c /* [RW] Receive Packet Counter */
#define BCHP_MIB1_GRBYT                          0x12c02c70 /* [RW] Receive Byte Counter */
#define BCHP_MIB1_GRUC                           0x12c02c74 /* [RW] Receive Unicast Packet Counter */
#define BCHP_MIB1_GRPOK                          0x12c02c78 /* [RW] Receive Good Packet Counter */
#define BCHP_MIB1_GRPPP                          0x12c02c7c /* [RW] Receive PPP Packet Counter */
#define BCHP_MIB1_GRCRC                          0x12c02c80 /* [RW] Receive CRC Match Packet Counter */
#define BCHP_MIB1_GTXPF                          0x12c02c84 /* [RW] Transmit Pause Frame Packet Counter */
#define BCHP_MIB1_GTJBR                          0x12c02c88 /* [RW] Transmit Jabber Counter */
#define BCHP_MIB1_GTFCS                          0x12c02c8c /* [RW] Transmit FCS Error Counter */
#define BCHP_MIB1_GTXCF                          0x12c02c90 /* [RW] Transmit Control Frame Packet Counter */
#define BCHP_MIB1_GTOVR                          0x12c02c94 /* [RW] Transmit Oversize Packet Counter */
#define BCHP_MIB1_GTDRF                          0x12c02c98 /* [RW] Transmit Deferral Packet Counter */
#define BCHP_MIB1_GTEDF                          0x12c02c9c /* [RW] Transmit Excessive Deferral Packet Counter */
#define BCHP_MIB1_GTSCL                          0x12c02ca0 /* [RW] Transmit Single Collision Packet Counter */
#define BCHP_MIB1_GTMCL                          0x12c02ca4 /* [RW] Transmit Multiple Collision Packet Counter */
#define BCHP_MIB1_GTLCL                          0x12c02ca8 /* [RW] Transmit Late Collision Packet Counter */
#define BCHP_MIB1_GTXCL                          0x12c02cac /* [RW] Transmit Excessive Collision Packet Counter */
#define BCHP_MIB1_GTFRG                          0x12c02cb0 /* [RW] Transmit Fragments Packet Counter */
#define BCHP_MIB1_GTNCL                          0x12c02cb4 /* [RW] Transmit Total Collision Counter */
#define BCHP_MIB1_GTMCA                          0x12c02cb8 /* [RW] Transmit Multicast Packet Counter */
#define BCHP_MIB1_GTBCA                          0x12c02cbc /* [RW] Transmit Broadcast Packet Counter */
#define BCHP_MIB1_TR64                           0x12c02cc0 /* [RW] Transmit 64B Frame Counter */
#define BCHP_MIB1_TR127                          0x12c02cc4 /* [RW] Transmit 65B to 127B Frame Counter */
#define BCHP_MIB1_TR255                          0x12c02cc8 /* [RW] Transmit 128B to 255B Frame Counter */
#define BCHP_MIB1_TR511                          0x12c02ccc /* [RW] Transmit 256B to 511B Frame Counter */
#define BCHP_MIB1_TR1023                         0x12c02cd0 /* [RW] Transmit 512B to 1023B Frame Counter */
#define BCHP_MIB1_TR1518                         0x12c02cd4 /* [RW] Transmit 1024B to 1518B Frame Counter */
#define BCHP_MIB1_TRMGV                          0x12c02cd8 /* [RW] Transmit 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB1_TR2047                         0x12c02cdc /* [RW] Transmit 1522B to 2047B Frame Counter */
#define BCHP_MIB1_TR4095                         0x12c02ce0 /* [RW] Transmit 2048B to 4095B Frame Counter */
#define BCHP_MIB1_TR9216                         0x12c02ce4 /* [RW] Transmit 4096B to 9216B Frame Counter */
#define BCHP_MIB1_GTPKT                          0x12c02ce8 /* [RW] Transmit Packet Counter */
#define BCHP_MIB1_GTBYT                          0x12c02cec /* [RW] Transmit Byte Counter */
#define BCHP_MIB1_GTUC                           0x12c02cf0 /* [RW] Transmit Unicast Packet Counter */
#define BCHP_MIB1_GTPOK                          0x12c02cf4 /* [RW] Transmit Good Packet Counter */

/***************************************************************************
 *GRFCS - Receive FCS Error Counter
 ***************************************************************************/
/* MIB1 :: GRFCS :: RO [31:00] */
#define BCHP_MIB1_GRFCS_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRFCS_RO_SHIFT                                   0

/***************************************************************************
 *GRXCF - Receive Control Frame Packet Counter
 ***************************************************************************/
/* MIB1 :: GRXCF :: RO [31:00] */
#define BCHP_MIB1_GRXCF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRXCF_RO_SHIFT                                   0

/***************************************************************************
 *GRXPF - Receive Pause Frame Packet Counter
 ***************************************************************************/
/* MIB1 :: GRXPF :: RO [31:00] */
#define BCHP_MIB1_GRXPF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRXPF_RO_SHIFT                                   0

/***************************************************************************
 *GRXUO - Receive Unknown OP Code Packet Counter
 ***************************************************************************/
/* MIB1 :: GRXUO :: RO [31:00] */
#define BCHP_MIB1_GRXUO_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRXUO_RO_SHIFT                                   0

/***************************************************************************
 *GRALN - Receive Alignmenet Error Counter
 ***************************************************************************/
/* MIB1 :: GRALN :: RO [31:00] */
#define BCHP_MIB1_GRALN_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRALN_RO_SHIFT                                   0

/***************************************************************************
 *GRFLR - Receive Frame Length Out Of Range Counter
 ***************************************************************************/
/* MIB1 :: GRFLR :: RO [31:00] */
#define BCHP_MIB1_GRFLR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRFLR_RO_SHIFT                                   0

/***************************************************************************
 *GRCDE - Receive Code Error Packet Counter
 ***************************************************************************/
/* MIB1 :: GRCDE :: RO [31:00] */
#define BCHP_MIB1_GRCDE_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRCDE_RO_SHIFT                                   0

/***************************************************************************
 *GRFCR - Receive Carrier Sense Error Packet Counter
 ***************************************************************************/
/* MIB1 :: GRFCR :: RO [31:00] */
#define BCHP_MIB1_GRFCR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRFCR_RO_SHIFT                                   0

/***************************************************************************
 *GROVR - Receive Oversize Packet Counter
 ***************************************************************************/
/* MIB1 :: GROVR :: RO [31:00] */
#define BCHP_MIB1_GROVR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GROVR_RO_SHIFT                                   0

/***************************************************************************
 *GRJBR - Receive Jabber Counter
 ***************************************************************************/
/* MIB1 :: GRJBR :: RO [31:00] */
#define BCHP_MIB1_GRJBR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRJBR_RO_SHIFT                                   0

/***************************************************************************
 *GRMTUE - Receive MTU Error Packet Counter
 ***************************************************************************/
/* MIB1 :: GRMTUE :: RO [31:00] */
#define BCHP_MIB1_GRMTUE_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GRMTUE_RO_SHIFT                                  0

/***************************************************************************
 *RRPKT - Receive RUNT Packet Counter
 ***************************************************************************/
/* MIB1 :: RRPKT :: RO [31:00] */
#define BCHP_MIB1_RRPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_RRPKT_RO_SHIFT                                   0

/***************************************************************************
 *RRUND - Receive RUNT Packet And Contain A Valid FCS
 ***************************************************************************/
/* MIB1 :: RRUND :: RO [31:00] */
#define BCHP_MIB1_RRUND_RO_MASK                                    0xffffffff
#define BCHP_MIB1_RRUND_RO_SHIFT                                   0

/***************************************************************************
 *RRFRG - Receive RUNT Packet And Contain Invalid FCS or Alignment Error
 ***************************************************************************/
/* MIB1 :: RRFRG :: RO [31:00] */
#define BCHP_MIB1_RRFRG_RO_MASK                                    0xffffffff
#define BCHP_MIB1_RRFRG_RO_SHIFT                                   0

/***************************************************************************
 *RRBYT - Receive RUNT Packet Byte Counter
 ***************************************************************************/
/* MIB1 :: RRBYT :: RO [31:00] */
#define BCHP_MIB1_RRBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_RRBYT_RO_SHIFT                                   0

/***************************************************************************
 *GRMCA - Receive Multicast Frame Counter
 ***************************************************************************/
/* MIB1 :: GRMCA :: RO [31:00] */
#define BCHP_MIB1_GRMCA_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRMCA_RO_SHIFT                                   0

/***************************************************************************
 *GRBCA - Receive Broadcast Frame Counter
 ***************************************************************************/
/* MIB1 :: GRBCA :: RO [31:00] */
#define BCHP_MIB1_GRBCA_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRBCA_RO_SHIFT                                   0

/***************************************************************************
 *GR64 - Receive 64B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR64 :: RO [31:00] */
#define BCHP_MIB1_GR64_RO_MASK                                     0xffffffff
#define BCHP_MIB1_GR64_RO_SHIFT                                    0

/***************************************************************************
 *GR127 - Receive 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR127 :: RO [31:00] */
#define BCHP_MIB1_GR127_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GR127_RO_SHIFT                                   0

/***************************************************************************
 *GR255 - Receive 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR255 :: RO [31:00] */
#define BCHP_MIB1_GR255_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GR255_RO_SHIFT                                   0

/***************************************************************************
 *GR511 - Receive 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR511 :: RO [31:00] */
#define BCHP_MIB1_GR511_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GR511_RO_SHIFT                                   0

/***************************************************************************
 *GR1023 - Receive 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR1023 :: RO [31:00] */
#define BCHP_MIB1_GR1023_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GR1023_RO_SHIFT                                  0

/***************************************************************************
 *GR1518 - Receive 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR1518 :: RO [31:00] */
#define BCHP_MIB1_GR1518_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GR1518_RO_SHIFT                                  0

/***************************************************************************
 *GRMGV - Receive 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB1 :: GRMGV :: RO [31:00] */
#define BCHP_MIB1_GRMGV_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRMGV_RO_SHIFT                                   0

/***************************************************************************
 *GR2047 - Receive 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR2047 :: RO [31:00] */
#define BCHP_MIB1_GR2047_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GR2047_RO_SHIFT                                  0

/***************************************************************************
 *GR4095 - Receive 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR4095 :: RO [31:00] */
#define BCHP_MIB1_GR4095_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GR4095_RO_SHIFT                                  0

/***************************************************************************
 *GR9216 - Receive 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB1 :: GR9216 :: RO [31:00] */
#define BCHP_MIB1_GR9216_RO_MASK                                   0xffffffff
#define BCHP_MIB1_GR9216_RO_SHIFT                                  0

/***************************************************************************
 *GRPKT - Receive Packet Counter
 ***************************************************************************/
/* MIB1 :: GRPKT :: RO [31:00] */
#define BCHP_MIB1_GRPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRPKT_RO_SHIFT                                   0

/***************************************************************************
 *GRBYT - Receive Byte Counter
 ***************************************************************************/
/* MIB1 :: GRBYT :: RO [31:00] */
#define BCHP_MIB1_GRBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRBYT_RO_SHIFT                                   0

/***************************************************************************
 *GRUC - Receive Unicast Packet Counter
 ***************************************************************************/
/* MIB1 :: GRUC :: RO [31:00] */
#define BCHP_MIB1_GRUC_RO_MASK                                     0xffffffff
#define BCHP_MIB1_GRUC_RO_SHIFT                                    0

/***************************************************************************
 *GRPOK - Receive Good Packet Counter
 ***************************************************************************/
/* MIB1 :: GRPOK :: RO [31:00] */
#define BCHP_MIB1_GRPOK_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRPOK_RO_SHIFT                                   0

/***************************************************************************
 *GRPPP - Receive PPP Packet Counter
 ***************************************************************************/
/* MIB1 :: GRPPP :: RO [31:00] */
#define BCHP_MIB1_GRPPP_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRPPP_RO_SHIFT                                   0

/***************************************************************************
 *GRCRC - Receive CRC Match Packet Counter
 ***************************************************************************/
/* MIB1 :: GRCRC :: RO [31:00] */
#define BCHP_MIB1_GRCRC_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GRCRC_RO_SHIFT                                   0

/***************************************************************************
 *GTXPF - Transmit Pause Frame Packet Counter
 ***************************************************************************/
/* MIB1 :: GTXPF :: RO [31:00] */
#define BCHP_MIB1_GTXPF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTXPF_RO_SHIFT                                   0

/***************************************************************************
 *GTJBR - Transmit Jabber Counter
 ***************************************************************************/
/* MIB1 :: GTJBR :: RO [31:00] */
#define BCHP_MIB1_GTJBR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTJBR_RO_SHIFT                                   0

/***************************************************************************
 *GTFCS - Transmit FCS Error Counter
 ***************************************************************************/
/* MIB1 :: GTFCS :: RO [31:00] */
#define BCHP_MIB1_GTFCS_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTFCS_RO_SHIFT                                   0

/***************************************************************************
 *GTXCF - Transmit Control Frame Packet Counter
 ***************************************************************************/
/* MIB1 :: GTXCF :: RO [31:00] */
#define BCHP_MIB1_GTXCF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTXCF_RO_SHIFT                                   0

/***************************************************************************
 *GTOVR - Transmit Oversize Packet Counter
 ***************************************************************************/
/* MIB1 :: GTOVR :: RO [31:00] */
#define BCHP_MIB1_GTOVR_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTOVR_RO_SHIFT                                   0

/***************************************************************************
 *GTDRF - Transmit Deferral Packet Counter
 ***************************************************************************/
/* MIB1 :: GTDRF :: RO [31:00] */
#define BCHP_MIB1_GTDRF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTDRF_RO_SHIFT                                   0

/***************************************************************************
 *GTEDF - Transmit Excessive Deferral Packet Counter
 ***************************************************************************/
/* MIB1 :: GTEDF :: RO [31:00] */
#define BCHP_MIB1_GTEDF_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTEDF_RO_SHIFT                                   0

/***************************************************************************
 *GTSCL - Transmit Single Collision Packet Counter
 ***************************************************************************/
/* MIB1 :: GTSCL :: RO [31:00] */
#define BCHP_MIB1_GTSCL_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTSCL_RO_SHIFT                                   0

/***************************************************************************
 *GTMCL - Transmit Multiple Collision Packet Counter
 ***************************************************************************/
/* MIB1 :: GTMCL :: RO [31:00] */
#define BCHP_MIB1_GTMCL_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTMCL_RO_SHIFT                                   0

/***************************************************************************
 *GTLCL - Transmit Late Collision Packet Counter
 ***************************************************************************/
/* MIB1 :: GTLCL :: RO [31:00] */
#define BCHP_MIB1_GTLCL_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTLCL_RO_SHIFT                                   0

/***************************************************************************
 *GTXCL - Transmit Excessive Collision Packet Counter
 ***************************************************************************/
/* MIB1 :: GTXCL :: RO [31:00] */
#define BCHP_MIB1_GTXCL_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTXCL_RO_SHIFT                                   0

/***************************************************************************
 *GTFRG - Transmit Fragments Packet Counter
 ***************************************************************************/
/* MIB1 :: GTFRG :: RO [31:00] */
#define BCHP_MIB1_GTFRG_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTFRG_RO_SHIFT                                   0

/***************************************************************************
 *GTNCL - Transmit Total Collision Counter
 ***************************************************************************/
/* MIB1 :: GTNCL :: RO [31:00] */
#define BCHP_MIB1_GTNCL_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTNCL_RO_SHIFT                                   0

/***************************************************************************
 *GTMCA - Transmit Multicast Packet Counter
 ***************************************************************************/
/* MIB1 :: GTMCA :: RO [31:00] */
#define BCHP_MIB1_GTMCA_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTMCA_RO_SHIFT                                   0

/***************************************************************************
 *GTBCA - Transmit Broadcast Packet Counter
 ***************************************************************************/
/* MIB1 :: GTBCA :: RO [31:00] */
#define BCHP_MIB1_GTBCA_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTBCA_RO_SHIFT                                   0

/***************************************************************************
 *TR64 - Transmit 64B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR64 :: RO [31:00] */
#define BCHP_MIB1_TR64_RO_MASK                                     0xffffffff
#define BCHP_MIB1_TR64_RO_SHIFT                                    0

/***************************************************************************
 *TR127 - Transmit 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR127 :: RO [31:00] */
#define BCHP_MIB1_TR127_RO_MASK                                    0xffffffff
#define BCHP_MIB1_TR127_RO_SHIFT                                   0

/***************************************************************************
 *TR255 - Transmit 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR255 :: RO [31:00] */
#define BCHP_MIB1_TR255_RO_MASK                                    0xffffffff
#define BCHP_MIB1_TR255_RO_SHIFT                                   0

/***************************************************************************
 *TR511 - Transmit 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR511 :: RO [31:00] */
#define BCHP_MIB1_TR511_RO_MASK                                    0xffffffff
#define BCHP_MIB1_TR511_RO_SHIFT                                   0

/***************************************************************************
 *TR1023 - Transmit 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR1023 :: RO [31:00] */
#define BCHP_MIB1_TR1023_RO_MASK                                   0xffffffff
#define BCHP_MIB1_TR1023_RO_SHIFT                                  0

/***************************************************************************
 *TR1518 - Transmit 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR1518 :: RO [31:00] */
#define BCHP_MIB1_TR1518_RO_MASK                                   0xffffffff
#define BCHP_MIB1_TR1518_RO_SHIFT                                  0

/***************************************************************************
 *TRMGV - Transmit 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB1 :: TRMGV :: RO [31:00] */
#define BCHP_MIB1_TRMGV_RO_MASK                                    0xffffffff
#define BCHP_MIB1_TRMGV_RO_SHIFT                                   0

/***************************************************************************
 *TR2047 - Transmit 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR2047 :: RO [31:00] */
#define BCHP_MIB1_TR2047_RO_MASK                                   0xffffffff
#define BCHP_MIB1_TR2047_RO_SHIFT                                  0

/***************************************************************************
 *TR4095 - Transmit 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR4095 :: RO [31:00] */
#define BCHP_MIB1_TR4095_RO_MASK                                   0xffffffff
#define BCHP_MIB1_TR4095_RO_SHIFT                                  0

/***************************************************************************
 *TR9216 - Transmit 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB1 :: TR9216 :: RO [31:00] */
#define BCHP_MIB1_TR9216_RO_MASK                                   0xffffffff
#define BCHP_MIB1_TR9216_RO_SHIFT                                  0

/***************************************************************************
 *GTPKT - Transmit Packet Counter
 ***************************************************************************/
/* MIB1 :: GTPKT :: RO [31:00] */
#define BCHP_MIB1_GTPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTPKT_RO_SHIFT                                   0

/***************************************************************************
 *GTBYT - Transmit Byte Counter
 ***************************************************************************/
/* MIB1 :: GTBYT :: RO [31:00] */
#define BCHP_MIB1_GTBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTBYT_RO_SHIFT                                   0

/***************************************************************************
 *GTUC - Transmit Unicast Packet Counter
 ***************************************************************************/
/* MIB1 :: GTUC :: RO [31:00] */
#define BCHP_MIB1_GTUC_RO_MASK                                     0xffffffff
#define BCHP_MIB1_GTUC_RO_SHIFT                                    0

/***************************************************************************
 *GTPOK - Transmit Good Packet Counter
 ***************************************************************************/
/* MIB1 :: GTPOK :: RO [31:00] */
#define BCHP_MIB1_GTPOK_RO_MASK                                    0xffffffff
#define BCHP_MIB1_GTPOK_RO_SHIFT                                   0

#endif /* #ifndef BCHP_MIB1_H__ */

/* End of File */
