/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Mar  3 03:33:07 2015
 *                 Full Compile MD5 Checksum  b5f19c74ab37a2906e9421a8b2559715
 *                     (minus title and desc)
 *                 MD5 Checksum               778db12b311d8f0cfe2c790ec2a4bd84
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_MBDMA_H__
#define BCHP_MBDMA_H__

/***************************************************************************
 *MBDMA - MBDMA Registers
 ***************************************************************************/
#define BCHP_MBDMA_STATUS                        0x12c00000 /* [RW] MBDMA Interrupt Status */
#define BCHP_MBDMA_TOKENCACHECTL                 0x12c00004 /* [RW] Token Free Cache Control */
#define BCHP_MBDMA_TOKENADDRESSFREE              0x12c00008 /* [RW] Free Pool Manager Token free address */
#define BCHP_MBDMA_GLOBALCTL                     0x12c0000c /* [RW] LAN MsgID, arbitration control and token cache flush */
#define BCHP_MBDMA_BUFFERBASE                    0x12c00010 /* [RW] Free pool buffer base address */
#define BCHP_MBDMA_UNUSED                        0x12c00014 /* [RW] Register not used, read zero, write produces error */
#define BCHP_MBDMA_CHANERR                       0x12c00018 /* [RO] Channel error indicators, one bit per channel */
#define BCHP_MBDMA_CHANERRMASK                   0x12c0001c /* [RW] Interrupt mask for channel error */
#define BCHP_MBDMA_BACKPRESSCTL0                 0x12c00020 /* [RW] Token allocation low and not low thresholds 8X and 4X tokens */
#define BCHP_MBDMA_BACKPRESSCTL1                 0x12c00024 /* [RW] Token allocation low and not low thresholds 2X and 1X tokens */
#define BCHP_MBDMA_DIAGOUT                       0x12c00028 /* [RO] Current diag output value */
#define BCHP_MBDMA_DIAGCOMPARE                   0x12c0002c /* [RW] Compare value for Diag interrupt */
#define BCHP_MBDMA_DIAGMASK                      0x12c00030 /* [RW] Diag compare mask for Diag interrupt */
#define BCHP_MBDMA_CAPTURESTATUS                 0x12c00034 /* [RO] Capture status flags for ubus capture trigger */
#define BCHP_MBDMA_CAPTUREMASK                   0x12c00038 /* [RW] Capture mask for ubus capture trigger */
#define BCHP_MBDMA_STATUS2                       0x12c0003c /* [RW] Reserved - Combined Interrupt Status */
#define BCHP_MBDMA_INTRMASK                      0x12c00040 /* [RW] Interrupt mask, ANDed with STATUS */
#define BCHP_MBDMA_TOKENCACHECTL2                0x12c00044 /* [RW] Token Allocation Cache Burst Control */
#define BCHP_MBDMA_TOKENCACHECTL3                0x12c00048 /* [RW] Token Allocation Cache Enables */
#define BCHP_MBDMA_TOKENADDRESS1X                0x12c0004c /* [RW] Free Pool Manager token allocation address for 1X tokens */
#define BCHP_MBDMA_TOKENADDRESS2X                0x12c00050 /* [RW] Free Pool Manager token allocation address for 2X tokens */
#define BCHP_MBDMA_TOKENADDRESS4X                0x12c00054 /* [RW] Free Pool Manager token allocation address for 4X tokens */
#define BCHP_MBDMA_TOKENADDRESS8X                0x12c00058 /* [RW] Free Pool Manager token allocation address for 8X tokens */
#define BCHP_MBDMA_TOKENBOUNDS                   0x12c0005c /* [RW] Token Cache memory bounds */
#define BCHP_MBDMA_TOKENSTATUS                   0x12c00060 /* [RO] Token allocation levels */
#define BCHP_MBDMA_TOKENSTATUS2                  0x12c00064 /* [RO] Token free level */
#define BCHP_MBDMA_PWRZONECTL                    0x12c00070 /* [RW] Secondary power zone control */
#define BCHP_MBDMA_FREQSCALECTL                  0x12c00074 /* [RW] Frequency scaler control */
#define BCHP_MBDMA_CHANCONTROL00                 0x12c00100 /* [RW] Channel 0 Rx control */
#define BCHP_MBDMA_LANMSGADDRESS00               0x12c00104 /* [RW] Target for LAN RX message for channel 0 */
#define BCHP_MBDMA_RXOFFSET00                    0x12c00108 /* [RW] Rx buffer offset for channel 0 */
#define BCHP_MBDMA_RXSTATUS00                    0x12c0010c /* [RW] Error status for channel 0 */
#define BCHP_MBDMA_CHANCONTROL01                 0x12c00120 /* [RW] Channel 1 Rx control */
#define BCHP_MBDMA_LANMSGADDRESS01               0x12c00124 /* [RW] Target for LAN RX message for channel 1 */
#define BCHP_MBDMA_RXOFFSET01                    0x12c00128 /* [RW] Rx buffer offset for channel 1 */
#define BCHP_MBDMA_RXSTATUS01                    0x12c0012c /* [RW] Error status for channel 1 */
#define BCHP_MBDMA_CHANCONTROL02                 0x12c00140 /* [RW] Channel 2 Tx control */
#define BCHP_MBDMA_LANMSGADDRESS02               0x12c00144 /* [RW] Target address for TX STATUS message for channel 2 */
#define BCHP_MBDMA_CHANCONTROL02_2               0x12c00148 /* [RW] Channel 2 Tx control register 2 */
#define BCHP_MBDMA_CHANCONTROL03                 0x12c00160 /* [RW] Channel 3 Tx control */
#define BCHP_MBDMA_LANMSGADDRESS03               0x12c00164 /* [RW] Target address for TX STATUS message for channel 3 */
#define BCHP_MBDMA_CHANCONTROL03_2               0x12c00168 /* [RW] Channel 3 Tx control register 2 */
#define BCHP_MBDMA_CHANCONTROL04                 0x12c00180 /* [RW] Channel 4 Tx control */
#define BCHP_MBDMA_LANMSGADDRESS04               0x12c00184 /* [RW] Target address for TX STATUS message for channel 4 */
#define BCHP_MBDMA_CHANCONTROL04_2               0x12c00188 /* [RW] Channel 4 Tx control register 2 */
#define BCHP_MBDMA_CHANCONTROL05                 0x12c001a0 /* [RW] Channel 5 Tx control */
#define BCHP_MBDMA_LANMSGADDRESS05               0x12c001a4 /* [RW] Target address for TX STATUS message for channel 5 */
#define BCHP_MBDMA_CHANCONTROL05_2               0x12c001a8 /* [RW] Channel 5 Tx control register 2 */
#define BCHP_MBDMA_LANTXMSGFIFO02                0x12c00500 /* [WO] LAN TX message FIFO for channel 02, Unimac0 low priority, MoCA queue priority 0 */
#define BCHP_MBDMA_LANTXMSGFIFO03                0x12c00508 /* [WO] LAN TX message FIFO for channel 03, Unimac0 high priority */
#define BCHP_MBDMA_LANTXMSGFIFO04                0x12c00510 /* [WO] LAN TX message FIFO for channel 04, Unimac1 low priority */
#define BCHP_MBDMA_LANTXMSGFIFO05                0x12c00518 /* [WO] LAN TX message FIFO for channel 05, Unimac1 high priority */

/***************************************************************************
 *STATUS - MBDMA Interrupt Status
 ***************************************************************************/
/* MBDMA :: STATUS :: reserved0 [31:17] */
#define BCHP_MBDMA_STATUS_reserved0_MASK                           0xfffe0000
#define BCHP_MBDMA_STATUS_reserved0_SHIFT                          17

/* MBDMA :: STATUS :: CHAN_ERR [16:16] */
#define BCHP_MBDMA_STATUS_CHAN_ERR_MASK                            0x00010000
#define BCHP_MBDMA_STATUS_CHAN_ERR_SHIFT                           16
#define BCHP_MBDMA_STATUS_CHAN_ERR_DEFAULT                         0x00000000

/* MBDMA :: STATUS :: TX_MSGQ_OVERFLOW [15:15] */
#define BCHP_MBDMA_STATUS_TX_MSGQ_OVERFLOW_MASK                    0x00008000
#define BCHP_MBDMA_STATUS_TX_MSGQ_OVERFLOW_SHIFT                   15
#define BCHP_MBDMA_STATUS_TX_MSGQ_OVERFLOW_DEFAULT                 0x00000000

/* MBDMA :: STATUS :: INVALID_TX_MSG_INTR [14:14] */
#define BCHP_MBDMA_STATUS_INVALID_TX_MSG_INTR_MASK                 0x00004000
#define BCHP_MBDMA_STATUS_INVALID_TX_MSG_INTR_SHIFT                14
#define BCHP_MBDMA_STATUS_INVALID_TX_MSG_INTR_DEFAULT              0x00000000

/* MBDMA :: STATUS :: DIAG_INTR [13:13] */
#define BCHP_MBDMA_STATUS_DIAG_INTR_MASK                           0x00002000
#define BCHP_MBDMA_STATUS_DIAG_INTR_SHIFT                          13
#define BCHP_MBDMA_STATUS_DIAG_INTR_DEFAULT                        0x00000000

/* MBDMA :: STATUS :: UBUS_ERROR [12:12] */
#define BCHP_MBDMA_STATUS_UBUS_ERROR_MASK                          0x00001000
#define BCHP_MBDMA_STATUS_UBUS_ERROR_SHIFT                         12
#define BCHP_MBDMA_STATUS_UBUS_ERROR_DEFAULT                       0x00000000

/* MBDMA :: STATUS :: TOKEN_RD_ERROR [11:11] */
#define BCHP_MBDMA_STATUS_TOKEN_RD_ERROR_MASK                      0x00000800
#define BCHP_MBDMA_STATUS_TOKEN_RD_ERROR_SHIFT                     11
#define BCHP_MBDMA_STATUS_TOKEN_RD_ERROR_DEFAULT                   0x00000000

/* MBDMA :: STATUS :: INVALID_TOKEN [10:10] */
#define BCHP_MBDMA_STATUS_INVALID_TOKEN_MASK                       0x00000400
#define BCHP_MBDMA_STATUS_INVALID_TOKEN_SHIFT                      10
#define BCHP_MBDMA_STATUS_INVALID_TOKEN_DEFAULT                    0x00000000

/* MBDMA :: STATUS :: ALLOC_FIFO_EMPTY_8X [09:09] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_8X_MASK                 0x00000200
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_8X_SHIFT                9
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_8X_DEFAULT              0x00000001

/* MBDMA :: STATUS :: ALLOC_FIFO_FULL_8X [08:08] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_8X_MASK                  0x00000100
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_8X_SHIFT                 8
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_8X_DEFAULT               0x00000000

/* MBDMA :: STATUS :: ALLOC_FIFO_EMPTY_4X [07:07] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_4X_MASK                 0x00000080
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_4X_SHIFT                7
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_4X_DEFAULT              0x00000001

/* MBDMA :: STATUS :: ALLOC_FIFO_FULL_4X [06:06] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_4X_MASK                  0x00000040
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_4X_SHIFT                 6
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_4X_DEFAULT               0x00000000

/* MBDMA :: STATUS :: ALLOC_FIFO_EMPTY_2X [05:05] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_2X_MASK                 0x00000020
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_2X_SHIFT                5
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_2X_DEFAULT              0x00000001

/* MBDMA :: STATUS :: ALLOC_FIFO_FULL_2X [04:04] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_2X_MASK                  0x00000010
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_2X_SHIFT                 4
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_2X_DEFAULT               0x00000000

/* MBDMA :: STATUS :: ALLOC_FIFO_EMPTY_1X [03:03] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_1X_MASK                 0x00000008
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_1X_SHIFT                3
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_EMPTY_1X_DEFAULT              0x00000001

/* MBDMA :: STATUS :: ALLOC_FIFO_FULL_1X [02:02] */
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_1X_MASK                  0x00000004
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_1X_SHIFT                 2
#define BCHP_MBDMA_STATUS_ALLOC_FIFO_FULL_1X_DEFAULT               0x00000000

/* MBDMA :: STATUS :: FREE_FIFO_EMPTY [01:01] */
#define BCHP_MBDMA_STATUS_FREE_FIFO_EMPTY_MASK                     0x00000002
#define BCHP_MBDMA_STATUS_FREE_FIFO_EMPTY_SHIFT                    1
#define BCHP_MBDMA_STATUS_FREE_FIFO_EMPTY_DEFAULT                  0x00000001

/* MBDMA :: STATUS :: FREE_FIFO_FULL [00:00] */
#define BCHP_MBDMA_STATUS_FREE_FIFO_FULL_MASK                      0x00000001
#define BCHP_MBDMA_STATUS_FREE_FIFO_FULL_SHIFT                     0
#define BCHP_MBDMA_STATUS_FREE_FIFO_FULL_DEFAULT                   0x00000000

/***************************************************************************
 *TOKENCACHECTL - Token Free Cache Control
 ***************************************************************************/
/* MBDMA :: TOKENCACHECTL :: reserved0 [31:18] */
#define BCHP_MBDMA_TOKENCACHECTL_reserved0_MASK                    0xfffc0000
#define BCHP_MBDMA_TOKENCACHECTL_reserved0_SHIFT                   18

/* MBDMA :: TOKENCACHECTL :: FORCE_2K_BUFFERS [17:17] */
#define BCHP_MBDMA_TOKENCACHECTL_FORCE_2K_BUFFERS_MASK             0x00020000
#define BCHP_MBDMA_TOKENCACHECTL_FORCE_2K_BUFFERS_SHIFT            17
#define BCHP_MBDMA_TOKENCACHECTL_FORCE_2K_BUFFERS_DEFAULT          0x00000000

/* MBDMA :: TOKENCACHECTL :: BUFF_SIZE [16:16] */
#define BCHP_MBDMA_TOKENCACHECTL_BUFF_SIZE_MASK                    0x00010000
#define BCHP_MBDMA_TOKENCACHECTL_BUFF_SIZE_SHIFT                   16
#define BCHP_MBDMA_TOKENCACHECTL_BUFF_SIZE_DEFAULT                 0x00000000

/* MBDMA :: TOKENCACHECTL :: FREE_ENABLE [15:15] */
#define BCHP_MBDMA_TOKENCACHECTL_FREE_ENABLE_MASK                  0x00008000
#define BCHP_MBDMA_TOKENCACHECTL_FREE_ENABLE_SHIFT                 15
#define BCHP_MBDMA_TOKENCACHECTL_FREE_ENABLE_DEFAULT               0x00000000

/* MBDMA :: TOKENCACHECTL :: reserved1 [14:13] */
#define BCHP_MBDMA_TOKENCACHECTL_reserved1_MASK                    0x00006000
#define BCHP_MBDMA_TOKENCACHECTL_reserved1_SHIFT                   13

/* MBDMA :: TOKENCACHECTL :: FREE_MAX_BURST [12:08] */
#define BCHP_MBDMA_TOKENCACHECTL_FREE_MAX_BURST_MASK               0x00001f00
#define BCHP_MBDMA_TOKENCACHECTL_FREE_MAX_BURST_SHIFT              8
#define BCHP_MBDMA_TOKENCACHECTL_FREE_MAX_BURST_DEFAULT            0x00000001

/* MBDMA :: TOKENCACHECTL :: FREE_THRESH [07:00] */
#define BCHP_MBDMA_TOKENCACHECTL_FREE_THRESH_MASK                  0x000000ff
#define BCHP_MBDMA_TOKENCACHECTL_FREE_THRESH_SHIFT                 0
#define BCHP_MBDMA_TOKENCACHECTL_FREE_THRESH_DEFAULT               0x00000008

/***************************************************************************
 *TOKENADDRESSFREE - Free Pool Manager Token free address
 ***************************************************************************/
/* MBDMA :: TOKENADDRESSFREE :: ADDRESS [31:00] */
#define BCHP_MBDMA_TOKENADDRESSFREE_ADDRESS_MASK                   0xffffffff
#define BCHP_MBDMA_TOKENADDRESSFREE_ADDRESS_SHIFT                  0
#define BCHP_MBDMA_TOKENADDRESSFREE_ADDRESS_DEFAULT                0x00000000

/***************************************************************************
 *GLOBALCTL - LAN MsgID, arbitration control and token cache flush
 ***************************************************************************/
/* MBDMA :: GLOBALCTL :: reserved0 [31:24] */
#define BCHP_MBDMA_GLOBALCTL_reserved0_MASK                        0xff000000
#define BCHP_MBDMA_GLOBALCTL_reserved0_SHIFT                       24

/* MBDMA :: GLOBALCTL :: FLUSH_CACHE [23:23] */
#define BCHP_MBDMA_GLOBALCTL_FLUSH_CACHE_MASK                      0x00800000
#define BCHP_MBDMA_GLOBALCTL_FLUSH_CACHE_SHIFT                     23
#define BCHP_MBDMA_GLOBALCTL_FLUSH_CACHE_DEFAULT                   0x00000000

/* MBDMA :: GLOBALCTL :: ALLOC_KEEP_ENABLE [22:22] */
#define BCHP_MBDMA_GLOBALCTL_ALLOC_KEEP_ENABLE_MASK                0x00400000
#define BCHP_MBDMA_GLOBALCTL_ALLOC_KEEP_ENABLE_SHIFT               22
#define BCHP_MBDMA_GLOBALCTL_ALLOC_KEEP_ENABLE_DEFAULT             0x00000000

/* MBDMA :: GLOBALCTL :: TOP_ARB_CTL [21:20] */
#define BCHP_MBDMA_GLOBALCTL_TOP_ARB_CTL_MASK                      0x00300000
#define BCHP_MBDMA_GLOBALCTL_TOP_ARB_CTL_SHIFT                     20
#define BCHP_MBDMA_GLOBALCTL_TOP_ARB_CTL_DEFAULT                   0x00000000

/* MBDMA :: GLOBALCTL :: RX_ARB_CTL [19:18] */
#define BCHP_MBDMA_GLOBALCTL_RX_ARB_CTL_MASK                       0x000c0000
#define BCHP_MBDMA_GLOBALCTL_RX_ARB_CTL_SHIFT                      18
#define BCHP_MBDMA_GLOBALCTL_RX_ARB_CTL_DEFAULT                    0x00000000

/* MBDMA :: GLOBALCTL :: TX_ARB_CTL [17:16] */
#define BCHP_MBDMA_GLOBALCTL_TX_ARB_CTL_MASK                       0x00030000
#define BCHP_MBDMA_GLOBALCTL_TX_ARB_CTL_SHIFT                      16
#define BCHP_MBDMA_GLOBALCTL_TX_ARB_CTL_DEFAULT                    0x00000000

/* MBDMA :: GLOBALCTL :: reserved1 [15:12] */
#define BCHP_MBDMA_GLOBALCTL_reserved1_MASK                        0x0000f000
#define BCHP_MBDMA_GLOBALCTL_reserved1_SHIFT                       12

/* MBDMA :: GLOBALCTL :: LAN_TX_MSG_ID_3W [11:06] */
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_3W_MASK                 0x00000fc0
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_3W_SHIFT                6
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_3W_DEFAULT              0x00000000

/* MBDMA :: GLOBALCTL :: LAN_TX_MSG_ID_2W [05:00] */
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_2W_MASK                 0x0000003f
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_2W_SHIFT                0
#define BCHP_MBDMA_GLOBALCTL_LAN_TX_MSG_ID_2W_DEFAULT              0x00000000

/***************************************************************************
 *BUFFERBASE - Free pool buffer base address
 ***************************************************************************/
/* MBDMA :: BUFFERBASE :: BUFF_BASE [31:00] */
#define BCHP_MBDMA_BUFFERBASE_BUFF_BASE_MASK                       0xffffffff
#define BCHP_MBDMA_BUFFERBASE_BUFF_BASE_SHIFT                      0
#define BCHP_MBDMA_BUFFERBASE_BUFF_BASE_DEFAULT                    0x00000000

/***************************************************************************
 *UNUSED - Register not used, read zero, write produces error
 ***************************************************************************/
/* MBDMA :: UNUSED :: reserved0 [31:00] */
#define BCHP_MBDMA_UNUSED_reserved0_MASK                           0xffffffff
#define BCHP_MBDMA_UNUSED_reserved0_SHIFT                          0

/***************************************************************************
 *CHANERR - Channel error indicators, one bit per channel
 ***************************************************************************/
/* MBDMA :: CHANERR :: reserved0 [31:02] */
#define BCHP_MBDMA_CHANERR_reserved0_MASK                          0xfffffffc
#define BCHP_MBDMA_CHANERR_reserved0_SHIFT                         2

/* MBDMA :: CHANERR :: CHANERR1 [01:01] */
#define BCHP_MBDMA_CHANERR_CHANERR1_MASK                           0x00000002
#define BCHP_MBDMA_CHANERR_CHANERR1_SHIFT                          1
#define BCHP_MBDMA_CHANERR_CHANERR1_DEFAULT                        0x00000000

/* MBDMA :: CHANERR :: CHANERR0 [00:00] */
#define BCHP_MBDMA_CHANERR_CHANERR0_MASK                           0x00000001
#define BCHP_MBDMA_CHANERR_CHANERR0_SHIFT                          0
#define BCHP_MBDMA_CHANERR_CHANERR0_DEFAULT                        0x00000000

/***************************************************************************
 *CHANERRMASK - Interrupt mask for channel error
 ***************************************************************************/
/* MBDMA :: CHANERRMASK :: reserved0 [31:02] */
#define BCHP_MBDMA_CHANERRMASK_reserved0_MASK                      0xfffffffc
#define BCHP_MBDMA_CHANERRMASK_reserved0_SHIFT                     2

/* MBDMA :: CHANERRMASK :: CHANERRMASK [01:00] */
#define BCHP_MBDMA_CHANERRMASK_CHANERRMASK_MASK                    0x00000003
#define BCHP_MBDMA_CHANERRMASK_CHANERRMASK_SHIFT                   0
#define BCHP_MBDMA_CHANERRMASK_CHANERRMASK_DEFAULT                 0x00000000

/***************************************************************************
 *BACKPRESSCTL0 - Token allocation low and not low thresholds 8X and 4X tokens
 ***************************************************************************/
/* MBDMA :: BACKPRESSCTL0 :: ALLOCNOTLOW8X [31:24] */
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW8X_MASK                0xff000000
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW8X_SHIFT               24
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW8X_DEFAULT             0x00000008

/* MBDMA :: BACKPRESSCTL0 :: ALLOCLOW8X [23:16] */
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW8X_MASK                   0x00ff0000
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW8X_SHIFT                  16
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW8X_DEFAULT                0x00000004

/* MBDMA :: BACKPRESSCTL0 :: ALLOCNOTLOW4X [15:08] */
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW4X_MASK                0x0000ff00
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW4X_SHIFT               8
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCNOTLOW4X_DEFAULT             0x00000008

/* MBDMA :: BACKPRESSCTL0 :: ALLOCLOW4X [07:00] */
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW4X_MASK                   0x000000ff
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW4X_SHIFT                  0
#define BCHP_MBDMA_BACKPRESSCTL0_ALLOCLOW4X_DEFAULT                0x00000004

/***************************************************************************
 *BACKPRESSCTL1 - Token allocation low and not low thresholds 2X and 1X tokens
 ***************************************************************************/
/* MBDMA :: BACKPRESSCTL1 :: ALLOCNOTLOW2X [31:24] */
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW2X_MASK                0xff000000
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW2X_SHIFT               24
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW2X_DEFAULT             0x00000008

/* MBDMA :: BACKPRESSCTL1 :: ALLOCLOW2X [23:16] */
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW2X_MASK                   0x00ff0000
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW2X_SHIFT                  16
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW2X_DEFAULT                0x00000004

/* MBDMA :: BACKPRESSCTL1 :: ALLOCNOTLOW1X [15:08] */
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW1X_MASK                0x0000ff00
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW1X_SHIFT               8
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCNOTLOW1X_DEFAULT             0x00000008

/* MBDMA :: BACKPRESSCTL1 :: ALLOCLOW1X [07:00] */
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW1X_MASK                   0x000000ff
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW1X_SHIFT                  0
#define BCHP_MBDMA_BACKPRESSCTL1_ALLOCLOW1X_DEFAULT                0x00000004

/***************************************************************************
 *DIAGOUT - Current diag output value
 ***************************************************************************/
/* MBDMA :: DIAGOUT :: DIAGOUT [31:00] */
#define BCHP_MBDMA_DIAGOUT_DIAGOUT_MASK                            0xffffffff
#define BCHP_MBDMA_DIAGOUT_DIAGOUT_SHIFT                           0

/***************************************************************************
 *DIAGCOMPARE - Compare value for Diag interrupt
 ***************************************************************************/
/* MBDMA :: DIAGCOMPARE :: DIAGCOMPARE [31:00] */
#define BCHP_MBDMA_DIAGCOMPARE_DIAGCOMPARE_MASK                    0xffffffff
#define BCHP_MBDMA_DIAGCOMPARE_DIAGCOMPARE_SHIFT                   0

/***************************************************************************
 *DIAGMASK - Diag compare mask for Diag interrupt
 ***************************************************************************/
/* MBDMA :: DIAGMASK :: DIAGMASK [31:00] */
#define BCHP_MBDMA_DIAGMASK_DIAGMASK_MASK                          0xffffffff
#define BCHP_MBDMA_DIAGMASK_DIAGMASK_SHIFT                         0

/***************************************************************************
 *CAPTURESTATUS - Capture status flags for ubus capture trigger
 ***************************************************************************/
/* MBDMA :: CAPTURESTATUS :: reserved0 [31:05] */
#define BCHP_MBDMA_CAPTURESTATUS_reserved0_MASK                    0xffffffe0
#define BCHP_MBDMA_CAPTURESTATUS_reserved0_SHIFT                   5

/* MBDMA :: CAPTURESTATUS :: DIAG_MATCH [04:04] */
#define BCHP_MBDMA_CAPTURESTATUS_DIAG_MATCH_MASK                   0x00000010
#define BCHP_MBDMA_CAPTURESTATUS_DIAG_MATCH_SHIFT                  4

/* MBDMA :: CAPTURESTATUS :: INVALID_MSG [03:03] */
#define BCHP_MBDMA_CAPTURESTATUS_INVALID_MSG_MASK                  0x00000008
#define BCHP_MBDMA_CAPTURESTATUS_INVALID_MSG_SHIFT                 3

/* MBDMA :: CAPTURESTATUS :: MSGQ_OVERFLOW [02:02] */
#define BCHP_MBDMA_CAPTURESTATUS_MSGQ_OVERFLOW_MASK                0x00000004
#define BCHP_MBDMA_CAPTURESTATUS_MSGQ_OVERFLOW_SHIFT               2

/* MBDMA :: CAPTURESTATUS :: TOKEN_RD_ERROR [01:01] */
#define BCHP_MBDMA_CAPTURESTATUS_TOKEN_RD_ERROR_MASK               0x00000002
#define BCHP_MBDMA_CAPTURESTATUS_TOKEN_RD_ERROR_SHIFT              1

/* MBDMA :: CAPTURESTATUS :: INVALID_TOKEN [00:00] */
#define BCHP_MBDMA_CAPTURESTATUS_INVALID_TOKEN_MASK                0x00000001
#define BCHP_MBDMA_CAPTURESTATUS_INVALID_TOKEN_SHIFT               0

/***************************************************************************
 *CAPTUREMASK - Capture mask for ubus capture trigger
 ***************************************************************************/
/* MBDMA :: CAPTUREMASK :: reserved0 [31:05] */
#define BCHP_MBDMA_CAPTUREMASK_reserved0_MASK                      0xffffffe0
#define BCHP_MBDMA_CAPTUREMASK_reserved0_SHIFT                     5

/* MBDMA :: CAPTUREMASK :: DIAG_MATCH_MASK [04:04] */
#define BCHP_MBDMA_CAPTUREMASK_DIAG_MATCH_MASK_MASK                0x00000010
#define BCHP_MBDMA_CAPTUREMASK_DIAG_MATCH_MASK_SHIFT               4

/* MBDMA :: CAPTUREMASK :: INVALID_MSG_MASK [03:03] */
#define BCHP_MBDMA_CAPTUREMASK_INVALID_MSG_MASK_MASK               0x00000008
#define BCHP_MBDMA_CAPTUREMASK_INVALID_MSG_MASK_SHIFT              3

/* MBDMA :: CAPTUREMASK :: MSGQ_OVERFLOW_MASK [02:02] */
#define BCHP_MBDMA_CAPTUREMASK_MSGQ_OVERFLOW_MASK_MASK             0x00000004
#define BCHP_MBDMA_CAPTUREMASK_MSGQ_OVERFLOW_MASK_SHIFT            2

/* MBDMA :: CAPTUREMASK :: TOKEN_RD_ERROR_MASK [01:01] */
#define BCHP_MBDMA_CAPTUREMASK_TOKEN_RD_ERROR_MASK_MASK            0x00000002
#define BCHP_MBDMA_CAPTUREMASK_TOKEN_RD_ERROR_MASK_SHIFT           1

/* MBDMA :: CAPTUREMASK :: INVALID_TOKEN_MASK [00:00] */
#define BCHP_MBDMA_CAPTUREMASK_INVALID_TOKEN_MASK_MASK             0x00000001
#define BCHP_MBDMA_CAPTUREMASK_INVALID_TOKEN_MASK_SHIFT            0

/***************************************************************************
 *STATUS2 - Reserved - Combined Interrupt Status
 ***************************************************************************/
/* MBDMA :: STATUS2 :: reserved0 [31:00] */
#define BCHP_MBDMA_STATUS2_reserved0_MASK                          0xffffffff
#define BCHP_MBDMA_STATUS2_reserved0_SHIFT                         0

/***************************************************************************
 *INTRMASK - Interrupt mask, ANDed with STATUS
 ***************************************************************************/
/* MBDMA :: INTRMASK :: MASK [31:00] */
#define BCHP_MBDMA_INTRMASK_MASK_MASK                              0xffffffff
#define BCHP_MBDMA_INTRMASK_MASK_SHIFT                             0
#define BCHP_MBDMA_INTRMASK_MASK_DEFAULT                           0x00000000

/***************************************************************************
 *TOKENCACHECTL2 - Token Allocation Cache Burst Control
 ***************************************************************************/
/* MBDMA :: TOKENCACHECTL2 :: BURST8X [31:24] */
#define BCHP_MBDMA_TOKENCACHECTL2_BURST8X_MASK                     0xff000000
#define BCHP_MBDMA_TOKENCACHECTL2_BURST8X_SHIFT                    24
#define BCHP_MBDMA_TOKENCACHECTL2_BURST8X_DEFAULT                  0x00000004

/* MBDMA :: TOKENCACHECTL2 :: BURST4X [23:16] */
#define BCHP_MBDMA_TOKENCACHECTL2_BURST4X_MASK                     0x00ff0000
#define BCHP_MBDMA_TOKENCACHECTL2_BURST4X_SHIFT                    16
#define BCHP_MBDMA_TOKENCACHECTL2_BURST4X_DEFAULT                  0x00000004

/* MBDMA :: TOKENCACHECTL2 :: BURST2X [15:08] */
#define BCHP_MBDMA_TOKENCACHECTL2_BURST2X_MASK                     0x0000ff00
#define BCHP_MBDMA_TOKENCACHECTL2_BURST2X_SHIFT                    8
#define BCHP_MBDMA_TOKENCACHECTL2_BURST2X_DEFAULT                  0x00000004

/* MBDMA :: TOKENCACHECTL2 :: BURST1X [07:00] */
#define BCHP_MBDMA_TOKENCACHECTL2_BURST1X_MASK                     0x000000ff
#define BCHP_MBDMA_TOKENCACHECTL2_BURST1X_SHIFT                    0
#define BCHP_MBDMA_TOKENCACHECTL2_BURST1X_DEFAULT                  0x00000004

/***************************************************************************
 *TOKENCACHECTL3 - Token Allocation Cache Enables
 ***************************************************************************/
/* MBDMA :: TOKENCACHECTL3 :: reserved0 [31:04] */
#define BCHP_MBDMA_TOKENCACHECTL3_reserved0_MASK                   0xfffffff0
#define BCHP_MBDMA_TOKENCACHECTL3_reserved0_SHIFT                  4

/* MBDMA :: TOKENCACHECTL3 :: ALLOC_ENABLE [03:00] */
#define BCHP_MBDMA_TOKENCACHECTL3_ALLOC_ENABLE_MASK                0x0000000f
#define BCHP_MBDMA_TOKENCACHECTL3_ALLOC_ENABLE_SHIFT               0
#define BCHP_MBDMA_TOKENCACHECTL3_ALLOC_ENABLE_DEFAULT             0x00000000

/***************************************************************************
 *TOKENADDRESS1X - Free Pool Manager token allocation address for 1X tokens
 ***************************************************************************/
/* MBDMA :: TOKENADDRESS1X :: ADDRESS [31:00] */
#define BCHP_MBDMA_TOKENADDRESS1X_ADDRESS_MASK                     0xffffffff
#define BCHP_MBDMA_TOKENADDRESS1X_ADDRESS_SHIFT                    0
#define BCHP_MBDMA_TOKENADDRESS1X_ADDRESS_DEFAULT                  0x00000000

/***************************************************************************
 *TOKENADDRESS2X - Free Pool Manager token allocation address for 2X tokens
 ***************************************************************************/
/* MBDMA :: TOKENADDRESS2X :: ADDRESS [31:00] */
#define BCHP_MBDMA_TOKENADDRESS2X_ADDRESS_MASK                     0xffffffff
#define BCHP_MBDMA_TOKENADDRESS2X_ADDRESS_SHIFT                    0
#define BCHP_MBDMA_TOKENADDRESS2X_ADDRESS_DEFAULT                  0x00000000

/***************************************************************************
 *TOKENADDRESS4X - Free Pool Manager token allocation address for 4X tokens
 ***************************************************************************/
/* MBDMA :: TOKENADDRESS4X :: ADDRESS [31:00] */
#define BCHP_MBDMA_TOKENADDRESS4X_ADDRESS_MASK                     0xffffffff
#define BCHP_MBDMA_TOKENADDRESS4X_ADDRESS_SHIFT                    0
#define BCHP_MBDMA_TOKENADDRESS4X_ADDRESS_DEFAULT                  0x00000000

/***************************************************************************
 *TOKENADDRESS8X - Free Pool Manager token allocation address for 8X tokens
 ***************************************************************************/
/* MBDMA :: TOKENADDRESS8X :: ADDRESS [31:00] */
#define BCHP_MBDMA_TOKENADDRESS8X_ADDRESS_MASK                     0xffffffff
#define BCHP_MBDMA_TOKENADDRESS8X_ADDRESS_SHIFT                    0
#define BCHP_MBDMA_TOKENADDRESS8X_ADDRESS_DEFAULT                  0x00000000

/***************************************************************************
 *TOKENBOUNDS - Token Cache memory bounds
 ***************************************************************************/
/* MBDMA :: TOKENBOUNDS :: BOUND3 [31:24] */
#define BCHP_MBDMA_TOKENBOUNDS_BOUND3_MASK                         0xff000000
#define BCHP_MBDMA_TOKENBOUNDS_BOUND3_SHIFT                        24
#define BCHP_MBDMA_TOKENBOUNDS_BOUND3_DEFAULT                      0x00000080

/* MBDMA :: TOKENBOUNDS :: BOUND2 [23:16] */
#define BCHP_MBDMA_TOKENBOUNDS_BOUND2_MASK                         0x00ff0000
#define BCHP_MBDMA_TOKENBOUNDS_BOUND2_SHIFT                        16
#define BCHP_MBDMA_TOKENBOUNDS_BOUND2_DEFAULT                      0x00000040

/* MBDMA :: TOKENBOUNDS :: BOUND1 [15:08] */
#define BCHP_MBDMA_TOKENBOUNDS_BOUND1_MASK                         0x0000ff00
#define BCHP_MBDMA_TOKENBOUNDS_BOUND1_SHIFT                        8
#define BCHP_MBDMA_TOKENBOUNDS_BOUND1_DEFAULT                      0x00000020

/* MBDMA :: TOKENBOUNDS :: BOUND0 [07:00] */
#define BCHP_MBDMA_TOKENBOUNDS_BOUND0_MASK                         0x000000ff
#define BCHP_MBDMA_TOKENBOUNDS_BOUND0_SHIFT                        0
#define BCHP_MBDMA_TOKENBOUNDS_BOUND0_DEFAULT                      0x00000010

/***************************************************************************
 *TOKENSTATUS - Token allocation levels
 ***************************************************************************/
/* MBDMA :: TOKENSTATUS :: LEVEL8X [31:24] */
#define BCHP_MBDMA_TOKENSTATUS_LEVEL8X_MASK                        0xff000000
#define BCHP_MBDMA_TOKENSTATUS_LEVEL8X_SHIFT                       24
#define BCHP_MBDMA_TOKENSTATUS_LEVEL8X_DEFAULT                     0x00000000

/* MBDMA :: TOKENSTATUS :: LEVEL4X [23:16] */
#define BCHP_MBDMA_TOKENSTATUS_LEVEL4X_MASK                        0x00ff0000
#define BCHP_MBDMA_TOKENSTATUS_LEVEL4X_SHIFT                       16
#define BCHP_MBDMA_TOKENSTATUS_LEVEL4X_DEFAULT                     0x00000000

/* MBDMA :: TOKENSTATUS :: LEVEL2X [15:08] */
#define BCHP_MBDMA_TOKENSTATUS_LEVEL2X_MASK                        0x0000ff00
#define BCHP_MBDMA_TOKENSTATUS_LEVEL2X_SHIFT                       8
#define BCHP_MBDMA_TOKENSTATUS_LEVEL2X_DEFAULT                     0x00000000

/* MBDMA :: TOKENSTATUS :: LEVEL1X [07:00] */
#define BCHP_MBDMA_TOKENSTATUS_LEVEL1X_MASK                        0x000000ff
#define BCHP_MBDMA_TOKENSTATUS_LEVEL1X_SHIFT                       0
#define BCHP_MBDMA_TOKENSTATUS_LEVEL1X_DEFAULT                     0x00000000

/***************************************************************************
 *TOKENSTATUS2 - Token free level
 ***************************************************************************/
/* MBDMA :: TOKENSTATUS2 :: reserved0 [31:08] */
#define BCHP_MBDMA_TOKENSTATUS2_reserved0_MASK                     0xffffff00
#define BCHP_MBDMA_TOKENSTATUS2_reserved0_SHIFT                    8

/* MBDMA :: TOKENSTATUS2 :: FREELEVEL [07:00] */
#define BCHP_MBDMA_TOKENSTATUS2_FREELEVEL_MASK                     0x000000ff
#define BCHP_MBDMA_TOKENSTATUS2_FREELEVEL_SHIFT                    0
#define BCHP_MBDMA_TOKENSTATUS2_FREELEVEL_DEFAULT                  0x00000000

/***************************************************************************
 *PWRZONECTL - Secondary power zone control
 ***************************************************************************/
/* MBDMA :: PWRZONECTL :: reserved0 [31:23] */
#define BCHP_MBDMA_PWRZONECTL_reserved0_MASK                       0xff800000
#define BCHP_MBDMA_PWRZONECTL_reserved0_SHIFT                      23

/* MBDMA :: PWRZONECTL :: PWRZONE1_upf_isolation [22:22] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_upf_isolation_MASK          0x00400000
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_upf_isolation_SHIFT         22
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_upf_isolation_DEFAULT       0x00000000

/* MBDMA :: PWRZONECTL :: PWRZONE1_psm_vdd [21:20] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_psm_vdd_MASK                0x00300000
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_psm_vdd_SHIFT               20
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_psm_vdd_DEFAULT             0x00000000

/* MBDMA :: PWRZONECTL :: reserved1 [19:18] */
#define BCHP_MBDMA_PWRZONECTL_reserved1_MASK                       0x000c0000
#define BCHP_MBDMA_PWRZONECTL_reserved1_SHIFT                      18

/* MBDMA :: PWRZONECTL :: PWRZONE1_soft_reset_n [17:17] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_soft_reset_n_MASK           0x00020000
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_soft_reset_n_SHIFT          17
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_soft_reset_n_DEFAULT        0x00000001

/* MBDMA :: PWRZONECTL :: PWRZONE1_clken [16:16] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_clken_MASK                  0x00010000
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_clken_SHIFT                 16
#define BCHP_MBDMA_PWRZONECTL_PWRZONE1_clken_DEFAULT               0x00000001

/* MBDMA :: PWRZONECTL :: reserved2 [15:07] */
#define BCHP_MBDMA_PWRZONECTL_reserved2_MASK                       0x0000ff80
#define BCHP_MBDMA_PWRZONECTL_reserved2_SHIFT                      7

/* MBDMA :: PWRZONECTL :: PWRZONE0_upf_isolation [06:06] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_upf_isolation_MASK          0x00000040
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_upf_isolation_SHIFT         6
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_upf_isolation_DEFAULT       0x00000000

/* MBDMA :: PWRZONECTL :: PWRZONE0_psm_vdd [05:04] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_psm_vdd_MASK                0x00000030
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_psm_vdd_SHIFT               4
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_psm_vdd_DEFAULT             0x00000000

/* MBDMA :: PWRZONECTL :: reserved3 [03:02] */
#define BCHP_MBDMA_PWRZONECTL_reserved3_MASK                       0x0000000c
#define BCHP_MBDMA_PWRZONECTL_reserved3_SHIFT                      2

/* MBDMA :: PWRZONECTL :: PWRZONE0_soft_reset_n [01:01] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_soft_reset_n_MASK           0x00000002
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_soft_reset_n_SHIFT          1
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_soft_reset_n_DEFAULT        0x00000001

/* MBDMA :: PWRZONECTL :: PWRZONE0_clken [00:00] */
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_clken_MASK                  0x00000001
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_clken_SHIFT                 0
#define BCHP_MBDMA_PWRZONECTL_PWRZONE0_clken_DEFAULT               0x00000001

/***************************************************************************
 *FREQSCALECTL - Frequency scaler control
 ***************************************************************************/
/* MBDMA :: FREQSCALECTL :: reserved0 [31:10] */
#define BCHP_MBDMA_FREQSCALECTL_reserved0_MASK                     0xfffffc00
#define BCHP_MBDMA_FREQSCALECTL_reserved0_SHIFT                    10

/* MBDMA :: FREQSCALECTL :: FREQSCALE_HI_DIV [09:07] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_HI_DIV_MASK              0x00000380
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_HI_DIV_SHIFT             7
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_HI_DIV_DEFAULT           0x00000000

/* MBDMA :: FREQSCALECTL :: FREQSCALE_LO_DIV [06:04] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_LO_DIV_MASK              0x00000070
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_LO_DIV_SHIFT             4
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_LO_DIV_DEFAULT           0x00000000

/* MBDMA :: FREQSCALECTL :: FREQSCALE_GEAR_SEL [03:03] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_GEAR_SEL_MASK            0x00000008
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_GEAR_SEL_SHIFT           3
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_GEAR_SEL_DEFAULT         0x00000000

/* MBDMA :: FREQSCALECTL :: FREQSCALE_DYN_GEAR_SEL [02:02] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_DYN_GEAR_SEL_MASK        0x00000004
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_DYN_GEAR_SEL_SHIFT       2
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_DYN_GEAR_SEL_DEFAULT     0x00000000

/* MBDMA :: FREQSCALECTL :: FREQSCALE_USE_DYN_GEAR_SEL [01:01] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_USE_DYN_GEAR_SEL_MASK    0x00000002
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_USE_DYN_GEAR_SEL_SHIFT   1

/* MBDMA :: FREQSCALECTL :: FREQSCALE_BYPASS_ENABLE [00:00] */
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_BYPASS_ENABLE_MASK       0x00000001
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_BYPASS_ENABLE_SHIFT      0
#define BCHP_MBDMA_FREQSCALECTL_FREQSCALE_BYPASS_ENABLE_DEFAULT    0x00000001

/***************************************************************************
 *CHANCONTROL00 - Channel 0 Rx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL00 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL00_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL00_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL00_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL00 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL00_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL00_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL00_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL00 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL00_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL00_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL00_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL00 :: ADDR_FORWARD [19:19] */
#define BCHP_MBDMA_CHANCONTROL00_ADDR_FORWARD_MASK                 0x00080000
#define BCHP_MBDMA_CHANCONTROL00_ADDR_FORWARD_SHIFT                19

/* MBDMA :: CHANCONTROL00 :: ERR_FORWARD [18:18] */
#define BCHP_MBDMA_CHANCONTROL00_ERR_FORWARD_MASK                  0x00040000
#define BCHP_MBDMA_CHANCONTROL00_ERR_FORWARD_SHIFT                 18

/* MBDMA :: CHANCONTROL00 :: MSG_ID [17:12] */
#define BCHP_MBDMA_CHANCONTROL00_MSG_ID_MASK                       0x0003f000
#define BCHP_MBDMA_CHANCONTROL00_MSG_ID_SHIFT                      12
#define BCHP_MBDMA_CHANCONTROL00_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL00 :: MAC_ID [11:08] */
#define BCHP_MBDMA_CHANCONTROL00_MAC_ID_MASK                       0x00000f00
#define BCHP_MBDMA_CHANCONTROL00_MAC_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL00_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL00 :: QOS [07:04] */
#define BCHP_MBDMA_CHANCONTROL00_QOS_MASK                          0x000000f0
#define BCHP_MBDMA_CHANCONTROL00_QOS_SHIFT                         4
#define BCHP_MBDMA_CHANCONTROL00_QOS_DEFAULT                       0x00000000

/* MBDMA :: CHANCONTROL00 :: BACKPRESSURE_SEL [03:00] */
#define BCHP_MBDMA_CHANCONTROL00_BACKPRESSURE_SEL_MASK             0x0000000f
#define BCHP_MBDMA_CHANCONTROL00_BACKPRESSURE_SEL_SHIFT            0
#define BCHP_MBDMA_CHANCONTROL00_BACKPRESSURE_SEL_DEFAULT          0x00000002

/***************************************************************************
 *LANMSGADDRESS00 - Target for LAN RX message for channel 0
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS00 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS00_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS00_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS00_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *RXOFFSET00 - Rx buffer offset for channel 0
 ***************************************************************************/
/* MBDMA :: RXOFFSET00 :: reserved0 [31:09] */
#define BCHP_MBDMA_RXOFFSET00_reserved0_MASK                       0xfffffe00
#define BCHP_MBDMA_RXOFFSET00_reserved0_SHIFT                      9

/* MBDMA :: RXOFFSET00 :: RX_BUFFER_OFFSET [08:00] */
#define BCHP_MBDMA_RXOFFSET00_RX_BUFFER_OFFSET_MASK                0x000001ff
#define BCHP_MBDMA_RXOFFSET00_RX_BUFFER_OFFSET_SHIFT               0
#define BCHP_MBDMA_RXOFFSET00_RX_BUFFER_OFFSET_DEFAULT             0x00000000

/***************************************************************************
 *RXSTATUS00 - Error status for channel 0
 ***************************************************************************/
/* MBDMA :: RXSTATUS00 :: reserved0 [31:06] */
#define BCHP_MBDMA_RXSTATUS00_reserved0_MASK                       0xffffffc0
#define BCHP_MBDMA_RXSTATUS00_reserved0_SHIFT                      6

/* MBDMA :: RXSTATUS00 :: RX_CHAN_CLIENT_ERR [05:05] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_CLIENT_ERR_MASK              0x00000020
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_CLIENT_ERR_SHIFT             5
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_CLIENT_ERR_DEFAULT           0x00000000

/* MBDMA :: RXSTATUS00 :: RX_CHAN_REQ_16X_NOT_EN [04:04] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_16X_NOT_EN_MASK          0x00000010
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_16X_NOT_EN_SHIFT         4
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_16X_NOT_EN_DEFAULT       0x00000000

/* MBDMA :: RXSTATUS00 :: RX_CHAN_REQ_8X_NOT_EN [03:03] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_8X_NOT_EN_MASK           0x00000008
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_8X_NOT_EN_SHIFT          3
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_8X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS00 :: RX_CHAN_REQ_4X_NOT_EN [02:02] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_4X_NOT_EN_MASK           0x00000004
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_4X_NOT_EN_SHIFT          2
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_4X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS00 :: RX_CHAN_REQ_2X_NOT_EN [01:01] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_2X_NOT_EN_MASK           0x00000002
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_2X_NOT_EN_SHIFT          1
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_2X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS00 :: RX_CHAN_REQ_1X_NOT_EN [00:00] */
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_1X_NOT_EN_MASK           0x00000001
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_1X_NOT_EN_SHIFT          0
#define BCHP_MBDMA_RXSTATUS00_RX_CHAN_REQ_1X_NOT_EN_DEFAULT        0x00000000

/***************************************************************************
 *CHANCONTROL01 - Channel 1 Rx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL01 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL01_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL01_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL01_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL01 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL01_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL01_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL01_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL01 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL01_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL01_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL01_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL01 :: ADDR_FORWARD [19:19] */
#define BCHP_MBDMA_CHANCONTROL01_ADDR_FORWARD_MASK                 0x00080000
#define BCHP_MBDMA_CHANCONTROL01_ADDR_FORWARD_SHIFT                19

/* MBDMA :: CHANCONTROL01 :: ERR_FORWARD [18:18] */
#define BCHP_MBDMA_CHANCONTROL01_ERR_FORWARD_MASK                  0x00040000
#define BCHP_MBDMA_CHANCONTROL01_ERR_FORWARD_SHIFT                 18

/* MBDMA :: CHANCONTROL01 :: MSG_ID [17:12] */
#define BCHP_MBDMA_CHANCONTROL01_MSG_ID_MASK                       0x0003f000
#define BCHP_MBDMA_CHANCONTROL01_MSG_ID_SHIFT                      12
#define BCHP_MBDMA_CHANCONTROL01_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL01 :: MAC_ID [11:08] */
#define BCHP_MBDMA_CHANCONTROL01_MAC_ID_MASK                       0x00000f00
#define BCHP_MBDMA_CHANCONTROL01_MAC_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL01_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL01 :: QOS [07:04] */
#define BCHP_MBDMA_CHANCONTROL01_QOS_MASK                          0x000000f0
#define BCHP_MBDMA_CHANCONTROL01_QOS_SHIFT                         4
#define BCHP_MBDMA_CHANCONTROL01_QOS_DEFAULT                       0x00000000

/* MBDMA :: CHANCONTROL01 :: BACKPRESSURE_SEL [03:00] */
#define BCHP_MBDMA_CHANCONTROL01_BACKPRESSURE_SEL_MASK             0x0000000f
#define BCHP_MBDMA_CHANCONTROL01_BACKPRESSURE_SEL_SHIFT            0
#define BCHP_MBDMA_CHANCONTROL01_BACKPRESSURE_SEL_DEFAULT          0x00000002

/***************************************************************************
 *LANMSGADDRESS01 - Target for LAN RX message for channel 1
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS01 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS01_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS01_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS01_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *RXOFFSET01 - Rx buffer offset for channel 1
 ***************************************************************************/
/* MBDMA :: RXOFFSET01 :: reserved0 [31:09] */
#define BCHP_MBDMA_RXOFFSET01_reserved0_MASK                       0xfffffe00
#define BCHP_MBDMA_RXOFFSET01_reserved0_SHIFT                      9

/* MBDMA :: RXOFFSET01 :: RX_BUFFER_OFFSET [08:00] */
#define BCHP_MBDMA_RXOFFSET01_RX_BUFFER_OFFSET_MASK                0x000001ff
#define BCHP_MBDMA_RXOFFSET01_RX_BUFFER_OFFSET_SHIFT               0
#define BCHP_MBDMA_RXOFFSET01_RX_BUFFER_OFFSET_DEFAULT             0x00000000

/***************************************************************************
 *RXSTATUS01 - Error status for channel 1
 ***************************************************************************/
/* MBDMA :: RXSTATUS01 :: reserved0 [31:06] */
#define BCHP_MBDMA_RXSTATUS01_reserved0_MASK                       0xffffffc0
#define BCHP_MBDMA_RXSTATUS01_reserved0_SHIFT                      6

/* MBDMA :: RXSTATUS01 :: RX_CHAN_CLIENT_ERR [05:05] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_CLIENT_ERR_MASK              0x00000020
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_CLIENT_ERR_SHIFT             5
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_CLIENT_ERR_DEFAULT           0x00000000

/* MBDMA :: RXSTATUS01 :: RX_CHAN_REQ_16X_NOT_EN [04:04] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_16X_NOT_EN_MASK          0x00000010
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_16X_NOT_EN_SHIFT         4
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_16X_NOT_EN_DEFAULT       0x00000000

/* MBDMA :: RXSTATUS01 :: RX_CHAN_REQ_8X_NOT_EN [03:03] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_8X_NOT_EN_MASK           0x00000008
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_8X_NOT_EN_SHIFT          3
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_8X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS01 :: RX_CHAN_REQ_4X_NOT_EN [02:02] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_4X_NOT_EN_MASK           0x00000004
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_4X_NOT_EN_SHIFT          2
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_4X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS01 :: RX_CHAN_REQ_2X_NOT_EN [01:01] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_2X_NOT_EN_MASK           0x00000002
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_2X_NOT_EN_SHIFT          1
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_2X_NOT_EN_DEFAULT        0x00000000

/* MBDMA :: RXSTATUS01 :: RX_CHAN_REQ_1X_NOT_EN [00:00] */
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_1X_NOT_EN_MASK           0x00000001
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_1X_NOT_EN_SHIFT          0
#define BCHP_MBDMA_RXSTATUS01_RX_CHAN_REQ_1X_NOT_EN_DEFAULT        0x00000000

/***************************************************************************
 *CHANCONTROL02 - Channel 2 Tx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL02 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL02_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL02_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL02_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL02 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL02_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL02_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL02_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL02 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL02_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL02_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL02_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL02 :: BACKPRESSURE_SEL [19:16] */
#define BCHP_MBDMA_CHANCONTROL02_BACKPRESSURE_SEL_MASK             0x000f0000
#define BCHP_MBDMA_CHANCONTROL02_BACKPRESSURE_SEL_SHIFT            16
#define BCHP_MBDMA_CHANCONTROL02_BACKPRESSURE_SEL_DEFAULT          0x00000002

/* MBDMA :: CHANCONTROL02 :: reserved0 [15:15] */
#define BCHP_MBDMA_CHANCONTROL02_reserved0_MASK                    0x00008000
#define BCHP_MBDMA_CHANCONTROL02_reserved0_SHIFT                   15

/* MBDMA :: CHANCONTROL02 :: TX_STAT_ON_ERROR [14:14] */
#define BCHP_MBDMA_CHANCONTROL02_TX_STAT_ON_ERROR_MASK             0x00004000
#define BCHP_MBDMA_CHANCONTROL02_TX_STAT_ON_ERROR_SHIFT            14
#define BCHP_MBDMA_CHANCONTROL02_TX_STAT_ON_ERROR_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL02 :: MSG_ID [13:08] */
#define BCHP_MBDMA_CHANCONTROL02_MSG_ID_MASK                       0x00003f00
#define BCHP_MBDMA_CHANCONTROL02_MSG_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL02_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL02 :: MAC_ID [07:04] */
#define BCHP_MBDMA_CHANCONTROL02_MAC_ID_MASK                       0x000000f0
#define BCHP_MBDMA_CHANCONTROL02_MAC_ID_SHIFT                      4
#define BCHP_MBDMA_CHANCONTROL02_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL02 :: MAX_REQS [03:00] */
#define BCHP_MBDMA_CHANCONTROL02_MAX_REQS_MASK                     0x0000000f
#define BCHP_MBDMA_CHANCONTROL02_MAX_REQS_SHIFT                    0
#define BCHP_MBDMA_CHANCONTROL02_MAX_REQS_DEFAULT                  0x00000001

/***************************************************************************
 *LANMSGADDRESS02 - Target address for TX STATUS message for channel 2
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS02 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS02_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS02_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS02_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *CHANCONTROL02_2 - Channel 2 Tx control register 2
 ***************************************************************************/
/* MBDMA :: CHANCONTROL02_2 :: reserved0 [31:17] */
#define BCHP_MBDMA_CHANCONTROL02_2_reserved0_MASK                  0xfffe0000
#define BCHP_MBDMA_CHANCONTROL02_2_reserved0_SHIFT                 17

/* MBDMA :: CHANCONTROL02_2 :: TX_MSGQ_OVERFLOW [16:16] */
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_OVERFLOW_MASK           0x00010000
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_OVERFLOW_SHIFT          16
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_OVERFLOW_DEFAULT        0x00000000

/* MBDMA :: CHANCONTROL02_2 :: TX_MSGQ_DEPTH [15:08] */
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_DEPTH_MASK              0x0000ff00
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_DEPTH_SHIFT             8
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_DEPTH_DEFAULT           0x00000020

/* MBDMA :: CHANCONTROL02_2 :: TX_MSGQ_NEAR_FULL_LEVEL [07:00] */
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_NEAR_FULL_LEVEL_MASK    0x000000ff
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_NEAR_FULL_LEVEL_SHIFT   0
#define BCHP_MBDMA_CHANCONTROL02_2_TX_MSGQ_NEAR_FULL_LEVEL_DEFAULT 0x00000010

/***************************************************************************
 *CHANCONTROL03 - Channel 3 Tx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL03 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL03_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL03_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL03_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL03 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL03_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL03_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL03_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL03 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL03_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL03_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL03_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL03 :: BACKPRESSURE_SEL [19:16] */
#define BCHP_MBDMA_CHANCONTROL03_BACKPRESSURE_SEL_MASK             0x000f0000
#define BCHP_MBDMA_CHANCONTROL03_BACKPRESSURE_SEL_SHIFT            16
#define BCHP_MBDMA_CHANCONTROL03_BACKPRESSURE_SEL_DEFAULT          0x00000002

/* MBDMA :: CHANCONTROL03 :: reserved0 [15:15] */
#define BCHP_MBDMA_CHANCONTROL03_reserved0_MASK                    0x00008000
#define BCHP_MBDMA_CHANCONTROL03_reserved0_SHIFT                   15

/* MBDMA :: CHANCONTROL03 :: TX_STAT_ON_ERROR [14:14] */
#define BCHP_MBDMA_CHANCONTROL03_TX_STAT_ON_ERROR_MASK             0x00004000
#define BCHP_MBDMA_CHANCONTROL03_TX_STAT_ON_ERROR_SHIFT            14
#define BCHP_MBDMA_CHANCONTROL03_TX_STAT_ON_ERROR_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL03 :: MSG_ID [13:08] */
#define BCHP_MBDMA_CHANCONTROL03_MSG_ID_MASK                       0x00003f00
#define BCHP_MBDMA_CHANCONTROL03_MSG_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL03_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL03 :: MAC_ID [07:04] */
#define BCHP_MBDMA_CHANCONTROL03_MAC_ID_MASK                       0x000000f0
#define BCHP_MBDMA_CHANCONTROL03_MAC_ID_SHIFT                      4
#define BCHP_MBDMA_CHANCONTROL03_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL03 :: MAX_REQS [03:00] */
#define BCHP_MBDMA_CHANCONTROL03_MAX_REQS_MASK                     0x0000000f
#define BCHP_MBDMA_CHANCONTROL03_MAX_REQS_SHIFT                    0
#define BCHP_MBDMA_CHANCONTROL03_MAX_REQS_DEFAULT                  0x00000001

/***************************************************************************
 *LANMSGADDRESS03 - Target address for TX STATUS message for channel 3
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS03 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS03_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS03_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS03_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *CHANCONTROL03_2 - Channel 3 Tx control register 2
 ***************************************************************************/
/* MBDMA :: CHANCONTROL03_2 :: reserved0 [31:17] */
#define BCHP_MBDMA_CHANCONTROL03_2_reserved0_MASK                  0xfffe0000
#define BCHP_MBDMA_CHANCONTROL03_2_reserved0_SHIFT                 17

/* MBDMA :: CHANCONTROL03_2 :: TX_MSGQ_OVERFLOW [16:16] */
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_OVERFLOW_MASK           0x00010000
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_OVERFLOW_SHIFT          16
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_OVERFLOW_DEFAULT        0x00000000

/* MBDMA :: CHANCONTROL03_2 :: TX_MSGQ_DEPTH [15:08] */
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_DEPTH_MASK              0x0000ff00
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_DEPTH_SHIFT             8
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_DEPTH_DEFAULT           0x00000020

/* MBDMA :: CHANCONTROL03_2 :: TX_MSGQ_NEAR_FULL_LEVEL [07:00] */
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_NEAR_FULL_LEVEL_MASK    0x000000ff
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_NEAR_FULL_LEVEL_SHIFT   0
#define BCHP_MBDMA_CHANCONTROL03_2_TX_MSGQ_NEAR_FULL_LEVEL_DEFAULT 0x00000010

/***************************************************************************
 *CHANCONTROL04 - Channel 4 Tx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL04 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL04_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL04_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL04_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL04 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL04_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL04_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL04_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL04 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL04_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL04_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL04_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL04 :: BACKPRESSURE_SEL [19:16] */
#define BCHP_MBDMA_CHANCONTROL04_BACKPRESSURE_SEL_MASK             0x000f0000
#define BCHP_MBDMA_CHANCONTROL04_BACKPRESSURE_SEL_SHIFT            16
#define BCHP_MBDMA_CHANCONTROL04_BACKPRESSURE_SEL_DEFAULT          0x00000002

/* MBDMA :: CHANCONTROL04 :: reserved0 [15:15] */
#define BCHP_MBDMA_CHANCONTROL04_reserved0_MASK                    0x00008000
#define BCHP_MBDMA_CHANCONTROL04_reserved0_SHIFT                   15

/* MBDMA :: CHANCONTROL04 :: TX_STAT_ON_ERROR [14:14] */
#define BCHP_MBDMA_CHANCONTROL04_TX_STAT_ON_ERROR_MASK             0x00004000
#define BCHP_MBDMA_CHANCONTROL04_TX_STAT_ON_ERROR_SHIFT            14
#define BCHP_MBDMA_CHANCONTROL04_TX_STAT_ON_ERROR_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL04 :: MSG_ID [13:08] */
#define BCHP_MBDMA_CHANCONTROL04_MSG_ID_MASK                       0x00003f00
#define BCHP_MBDMA_CHANCONTROL04_MSG_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL04_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL04 :: MAC_ID [07:04] */
#define BCHP_MBDMA_CHANCONTROL04_MAC_ID_MASK                       0x000000f0
#define BCHP_MBDMA_CHANCONTROL04_MAC_ID_SHIFT                      4
#define BCHP_MBDMA_CHANCONTROL04_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL04 :: MAX_REQS [03:00] */
#define BCHP_MBDMA_CHANCONTROL04_MAX_REQS_MASK                     0x0000000f
#define BCHP_MBDMA_CHANCONTROL04_MAX_REQS_SHIFT                    0
#define BCHP_MBDMA_CHANCONTROL04_MAX_REQS_DEFAULT                  0x00000001

/***************************************************************************
 *LANMSGADDRESS04 - Target address for TX STATUS message for channel 4
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS04 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS04_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS04_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS04_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *CHANCONTROL04_2 - Channel 4 Tx control register 2
 ***************************************************************************/
/* MBDMA :: CHANCONTROL04_2 :: reserved0 [31:17] */
#define BCHP_MBDMA_CHANCONTROL04_2_reserved0_MASK                  0xfffe0000
#define BCHP_MBDMA_CHANCONTROL04_2_reserved0_SHIFT                 17

/* MBDMA :: CHANCONTROL04_2 :: TX_MSGQ_OVERFLOW [16:16] */
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_OVERFLOW_MASK           0x00010000
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_OVERFLOW_SHIFT          16
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_OVERFLOW_DEFAULT        0x00000000

/* MBDMA :: CHANCONTROL04_2 :: TX_MSGQ_DEPTH [15:08] */
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_DEPTH_MASK              0x0000ff00
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_DEPTH_SHIFT             8
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_DEPTH_DEFAULT           0x00000020

/* MBDMA :: CHANCONTROL04_2 :: TX_MSGQ_NEAR_FULL_LEVEL [07:00] */
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_NEAR_FULL_LEVEL_MASK    0x000000ff
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_NEAR_FULL_LEVEL_SHIFT   0
#define BCHP_MBDMA_CHANCONTROL04_2_TX_MSGQ_NEAR_FULL_LEVEL_DEFAULT 0x00000010

/***************************************************************************
 *CHANCONTROL05 - Channel 5 Tx control
 ***************************************************************************/
/* MBDMA :: CHANCONTROL05 :: START_STOP_FLUSH [31:30] */
#define BCHP_MBDMA_CHANCONTROL05_START_STOP_FLUSH_MASK             0xc0000000
#define BCHP_MBDMA_CHANCONTROL05_START_STOP_FLUSH_SHIFT            30
#define BCHP_MBDMA_CHANCONTROL05_START_STOP_FLUSH_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL05 :: EAV_MODE [29:29] */
#define BCHP_MBDMA_CHANCONTROL05_EAV_MODE_MASK                     0x20000000
#define BCHP_MBDMA_CHANCONTROL05_EAV_MODE_SHIFT                    29
#define BCHP_MBDMA_CHANCONTROL05_EAV_MODE_DEFAULT                  0x00000000

/* MBDMA :: CHANCONTROL05 :: MAX_BURST [28:20] */
#define BCHP_MBDMA_CHANCONTROL05_MAX_BURST_MASK                    0x1ff00000
#define BCHP_MBDMA_CHANCONTROL05_MAX_BURST_SHIFT                   20
#define BCHP_MBDMA_CHANCONTROL05_MAX_BURST_DEFAULT                 0x00000010

/* MBDMA :: CHANCONTROL05 :: BACKPRESSURE_SEL [19:16] */
#define BCHP_MBDMA_CHANCONTROL05_BACKPRESSURE_SEL_MASK             0x000f0000
#define BCHP_MBDMA_CHANCONTROL05_BACKPRESSURE_SEL_SHIFT            16
#define BCHP_MBDMA_CHANCONTROL05_BACKPRESSURE_SEL_DEFAULT          0x00000002

/* MBDMA :: CHANCONTROL05 :: reserved0 [15:15] */
#define BCHP_MBDMA_CHANCONTROL05_reserved0_MASK                    0x00008000
#define BCHP_MBDMA_CHANCONTROL05_reserved0_SHIFT                   15

/* MBDMA :: CHANCONTROL05 :: TX_STAT_ON_ERROR [14:14] */
#define BCHP_MBDMA_CHANCONTROL05_TX_STAT_ON_ERROR_MASK             0x00004000
#define BCHP_MBDMA_CHANCONTROL05_TX_STAT_ON_ERROR_SHIFT            14
#define BCHP_MBDMA_CHANCONTROL05_TX_STAT_ON_ERROR_DEFAULT          0x00000000

/* MBDMA :: CHANCONTROL05 :: MSG_ID [13:08] */
#define BCHP_MBDMA_CHANCONTROL05_MSG_ID_MASK                       0x00003f00
#define BCHP_MBDMA_CHANCONTROL05_MSG_ID_SHIFT                      8
#define BCHP_MBDMA_CHANCONTROL05_MSG_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL05 :: MAC_ID [07:04] */
#define BCHP_MBDMA_CHANCONTROL05_MAC_ID_MASK                       0x000000f0
#define BCHP_MBDMA_CHANCONTROL05_MAC_ID_SHIFT                      4
#define BCHP_MBDMA_CHANCONTROL05_MAC_ID_DEFAULT                    0x00000000

/* MBDMA :: CHANCONTROL05 :: MAX_REQS [03:00] */
#define BCHP_MBDMA_CHANCONTROL05_MAX_REQS_MASK                     0x0000000f
#define BCHP_MBDMA_CHANCONTROL05_MAX_REQS_SHIFT                    0
#define BCHP_MBDMA_CHANCONTROL05_MAX_REQS_DEFAULT                  0x00000001

/***************************************************************************
 *LANMSGADDRESS05 - Target address for TX STATUS message for channel 5
 ***************************************************************************/
/* MBDMA :: LANMSGADDRESS05 :: ADDRESS [31:00] */
#define BCHP_MBDMA_LANMSGADDRESS05_ADDRESS_MASK                    0xffffffff
#define BCHP_MBDMA_LANMSGADDRESS05_ADDRESS_SHIFT                   0
#define BCHP_MBDMA_LANMSGADDRESS05_ADDRESS_DEFAULT                 0x00000000

/***************************************************************************
 *CHANCONTROL05_2 - Channel 5 Tx control register 2
 ***************************************************************************/
/* MBDMA :: CHANCONTROL05_2 :: reserved0 [31:17] */
#define BCHP_MBDMA_CHANCONTROL05_2_reserved0_MASK                  0xfffe0000
#define BCHP_MBDMA_CHANCONTROL05_2_reserved0_SHIFT                 17

/* MBDMA :: CHANCONTROL05_2 :: TX_MSGQ_OVERFLOW [16:16] */
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_OVERFLOW_MASK           0x00010000
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_OVERFLOW_SHIFT          16
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_OVERFLOW_DEFAULT        0x00000000

/* MBDMA :: CHANCONTROL05_2 :: TX_MSGQ_DEPTH [15:08] */
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_DEPTH_MASK              0x0000ff00
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_DEPTH_SHIFT             8
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_DEPTH_DEFAULT           0x00000020

/* MBDMA :: CHANCONTROL05_2 :: TX_MSGQ_NEAR_FULL_LEVEL [07:00] */
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_NEAR_FULL_LEVEL_MASK    0x000000ff
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_NEAR_FULL_LEVEL_SHIFT   0
#define BCHP_MBDMA_CHANCONTROL05_2_TX_MSGQ_NEAR_FULL_LEVEL_DEFAULT 0x00000010

/***************************************************************************
 *LANTXMSGFIFO02 - LAN TX message FIFO for channel 02, Unimac0 low priority, MoCA queue priority 0
 ***************************************************************************/
/* MBDMA :: LANTXMSGFIFO02 :: LANTXFIFOMSG [31:00] */
#define BCHP_MBDMA_LANTXMSGFIFO02_LANTXFIFOMSG_MASK                0xffffffff
#define BCHP_MBDMA_LANTXMSGFIFO02_LANTXFIFOMSG_SHIFT               0

/***************************************************************************
 *LANTXMSGFIFO03 - LAN TX message FIFO for channel 03, Unimac0 high priority
 ***************************************************************************/
/* MBDMA :: LANTXMSGFIFO03 :: LANTXFIFOMSG [31:00] */
#define BCHP_MBDMA_LANTXMSGFIFO03_LANTXFIFOMSG_MASK                0xffffffff
#define BCHP_MBDMA_LANTXMSGFIFO03_LANTXFIFOMSG_SHIFT               0

/***************************************************************************
 *LANTXMSGFIFO04 - LAN TX message FIFO for channel 04, Unimac1 low priority
 ***************************************************************************/
/* MBDMA :: LANTXMSGFIFO04 :: LANTXFIFOMSG [31:00] */
#define BCHP_MBDMA_LANTXMSGFIFO04_LANTXFIFOMSG_MASK                0xffffffff
#define BCHP_MBDMA_LANTXMSGFIFO04_LANTXFIFOMSG_SHIFT               0

/***************************************************************************
 *LANTXMSGFIFO05 - LAN TX message FIFO for channel 05, Unimac1 high priority
 ***************************************************************************/
/* MBDMA :: LANTXMSGFIFO05 :: LANTXFIFOMSG [31:00] */
#define BCHP_MBDMA_LANTXMSGFIFO05_LANTXFIFOMSG_MASK                0xffffffff
#define BCHP_MBDMA_LANTXMSGFIFO05_LANTXFIFOMSG_SHIFT               0

#endif /* #ifndef BCHP_MBDMA_H__ */

/* End of File */
