/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Mar  3 03:33:08 2015
 *                 Full Compile MD5 Checksum  b5f19c74ab37a2906e9421a8b2559715
 *                     (minus title and desc)
 *                 MD5 Checksum               778db12b311d8f0cfe2c790ec2a4bd84
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_DBG_PER_H__
#define BCHP_DBG_PER_H__

/***************************************************************************
 *Dbg_PER - Software debug Registers
 ***************************************************************************/
#define BCHP_Dbg_PER_Features                    0x14e003e0 /* [RW] Features Register for Software debug */
#define BCHP_Dbg_PER_SoftwareDebug1              0x14e003e4 /* [RW] Software debug register 1 */
#define BCHP_Dbg_PER_SoftwareDebug2              0x14e003e8 /* [RW] Software debug register 2 */
#define BCHP_Dbg_PER_SoftwareDebug3              0x14e003ec /* [RW] Software debug register 3 */
#define BCHP_Dbg_PER_SoftwareDebug4              0x14e003f0 /* [RW] Software debug register 4 */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1             0x14e003f4 /* [RW] ExtIrq Mux select 1 */

/***************************************************************************
 *Features - Features Register for Software debug
 ***************************************************************************/
/* Dbg_PER :: Features :: NotUsed [31:05] */
#define BCHP_Dbg_PER_Features_NotUsed_MASK                         0xffffffe0
#define BCHP_Dbg_PER_Features_NotUsed_SHIFT                        5
#define BCHP_Dbg_PER_Features_NotUsed_DEFAULT                      0x00000000

/* Dbg_PER :: Features :: DEVICENUM [04:04] */
#define BCHP_Dbg_PER_Features_DEVICENUM_MASK                       0x00000010
#define BCHP_Dbg_PER_Features_DEVICENUM_SHIFT                      4
#define BCHP_Dbg_PER_Features_DEVICENUM_DEFAULT                    0x00000000

/* Dbg_PER :: Features :: IDDQ [03:03] */
#define BCHP_Dbg_PER_Features_IDDQ_MASK                            0x00000008
#define BCHP_Dbg_PER_Features_IDDQ_SHIFT                           3
#define BCHP_Dbg_PER_Features_IDDQ_DEFAULT                         0x00000000

/* Dbg_PER :: Features :: DSWFE_DAISY_UP [02:02] */
#define BCHP_Dbg_PER_Features_DSWFE_DAISY_UP_MASK                  0x00000004
#define BCHP_Dbg_PER_Features_DSWFE_DAISY_UP_SHIFT                 2
#define BCHP_Dbg_PER_Features_DSWFE_DAISY_UP_DEFAULT               0x00000000

/* Dbg_PER :: Features :: UFE_LOOP_THRU [01:01] */
#define BCHP_Dbg_PER_Features_UFE_LOOP_THRU_MASK                   0x00000002
#define BCHP_Dbg_PER_Features_UFE_LOOP_THRU_SHIFT                  1
#define BCHP_Dbg_PER_Features_UFE_LOOP_THRU_DEFAULT                0x00000000

/* Dbg_PER :: Features :: UFE_DAISY_CHAIN [00:00] */
#define BCHP_Dbg_PER_Features_UFE_DAISY_CHAIN_MASK                 0x00000001
#define BCHP_Dbg_PER_Features_UFE_DAISY_CHAIN_SHIFT                0
#define BCHP_Dbg_PER_Features_UFE_DAISY_CHAIN_DEFAULT              0x00000000

/***************************************************************************
 *SoftwareDebug1 - Software debug register 1
 ***************************************************************************/
/* Dbg_PER :: SoftwareDebug1 :: SWDbg1 [31:00] */
#define BCHP_Dbg_PER_SoftwareDebug1_SWDbg1_MASK                    0xffffffff
#define BCHP_Dbg_PER_SoftwareDebug1_SWDbg1_SHIFT                   0
#define BCHP_Dbg_PER_SoftwareDebug1_SWDbg1_DEFAULT                 0x00000000

/***************************************************************************
 *SoftwareDebug2 - Software debug register 2
 ***************************************************************************/
/* Dbg_PER :: SoftwareDebug2 :: SWDbg2 [31:00] */
#define BCHP_Dbg_PER_SoftwareDebug2_SWDbg2_MASK                    0xffffffff
#define BCHP_Dbg_PER_SoftwareDebug2_SWDbg2_SHIFT                   0
#define BCHP_Dbg_PER_SoftwareDebug2_SWDbg2_DEFAULT                 0x00000000

/***************************************************************************
 *SoftwareDebug3 - Software debug register 3
 ***************************************************************************/
/* Dbg_PER :: SoftwareDebug3 :: SWDbg3 [31:00] */
#define BCHP_Dbg_PER_SoftwareDebug3_SWDbg3_MASK                    0xffffffff
#define BCHP_Dbg_PER_SoftwareDebug3_SWDbg3_SHIFT                   0
#define BCHP_Dbg_PER_SoftwareDebug3_SWDbg3_DEFAULT                 0x00000000

/***************************************************************************
 *SoftwareDebug4 - Software debug register 4
 ***************************************************************************/
/* Dbg_PER :: SoftwareDebug4 :: SWDbg4 [31:00] */
#define BCHP_Dbg_PER_SoftwareDebug4_SWDbg4_MASK                    0xffffffff
#define BCHP_Dbg_PER_SoftwareDebug4_SWDbg4_SHIFT                   0
#define BCHP_Dbg_PER_SoftwareDebug4_SWDbg4_DEFAULT                 0x00000000

/***************************************************************************
 *EXTIRQMUXSEL0_1 - ExtIrq Mux select 1
 ***************************************************************************/
/* Dbg_PER :: EXTIRQMUXSEL0_1 :: reserved0 [31:24] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_reserved0_MASK                0xff000000
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_reserved0_SHIFT               24

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ5_SEL [23:20] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ5_SEL_MASK             0x00f00000
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ5_SEL_SHIFT            20
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ5_SEL_DEFAULT          0x00000000

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ4_SEL [19:16] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ4_SEL_MASK             0x000f0000
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ4_SEL_SHIFT            16
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ4_SEL_DEFAULT          0x00000000

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ3_SEL [15:12] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ3_SEL_MASK             0x0000f000
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ3_SEL_SHIFT            12
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ3_SEL_DEFAULT          0x00000000

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ2_SEL [11:08] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ2_SEL_MASK             0x00000f00
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ2_SEL_SHIFT            8
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ2_SEL_DEFAULT          0x00000000

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ1_SEL [07:04] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ1_SEL_MASK             0x000000f0
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ1_SEL_SHIFT            4
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ1_SEL_DEFAULT          0x00000000

/* Dbg_PER :: EXTIRQMUXSEL0_1 :: EXT_IRQ0_SEL [03:00] */
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ0_SEL_MASK             0x0000000f
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ0_SEL_SHIFT            0
#define BCHP_Dbg_PER_EXTIRQMUXSEL0_1_EXT_IRQ0_SEL_DEFAULT          0x00000000

#endif /* #ifndef BCHP_DBG_PER_H__ */

/* End of File */
