/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Nov 14 03:20:37 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_FPM_SEARCH_FPM_H__
#define BCHP_FPM_SEARCH_FPM_H__

/***************************************************************************
 *FPM_SEARCH_FPM - FPM Search Tree Memory Access FPM
 ***************************************************************************/

/***************************************************************************
 *search_data%i - Search tree memory space.
 ***************************************************************************/
#define BCHP_FPM_SEARCH_FPM_search_datai_ARRAY_BASE                0x0000000012204000
#define BCHP_FPM_SEARCH_FPM_search_datai_ARRAY_START               0
#define BCHP_FPM_SEARCH_FPM_search_datai_ARRAY_END                 279
#define BCHP_FPM_SEARCH_FPM_search_datai_ARRAY_ELEMENT_SIZE        64

/***************************************************************************
 *search_data%i - Search tree memory space.
 ***************************************************************************/
/* FPM_SEARCH_FPM :: search_datai :: reserved0 [63:48] */
#define BCHP_FPM_SEARCH_FPM_search_datai_reserved0_MASK            0xffff000000000000
#define BCHP_FPM_SEARCH_FPM_search_datai_reserved0_SHIFT           48

/* FPM_SEARCH_FPM :: search_datai :: SearchData15 [47:45] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData15_MASK         0x0000e00000000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData15_SHIFT        45

/* FPM_SEARCH_FPM :: search_datai :: SearchData14 [44:42] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData14_MASK         0x00001c0000000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData14_SHIFT        42

/* FPM_SEARCH_FPM :: search_datai :: SearchData13 [41:39] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData13_MASK         0x0000038000000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData13_SHIFT        39

/* FPM_SEARCH_FPM :: search_datai :: SearchData12 [38:36] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData12_MASK         0x0000007000000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData12_SHIFT        36

/* FPM_SEARCH_FPM :: search_datai :: SearchData11 [35:33] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData11_MASK         0x0000000e00000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData11_SHIFT        33

/* FPM_SEARCH_FPM :: search_datai :: SearchData10 [32:30] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData10_MASK         0x00000001c0000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData10_SHIFT        30

/* FPM_SEARCH_FPM :: search_datai :: SearchData9 [29:27] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData9_MASK          0x0000000038000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData9_SHIFT         27

/* FPM_SEARCH_FPM :: search_datai :: SearchData8 [26:24] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData8_MASK          0x0000000007000000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData8_SHIFT         24

/* FPM_SEARCH_FPM :: search_datai :: SearchData7 [23:21] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData7_MASK          0x0000000000e00000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData7_SHIFT         21

/* FPM_SEARCH_FPM :: search_datai :: SearchData6 [20:18] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData6_MASK          0x00000000001c0000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData6_SHIFT         18

/* FPM_SEARCH_FPM :: search_datai :: SearchData5 [17:15] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData5_MASK          0x0000000000038000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData5_SHIFT         15

/* FPM_SEARCH_FPM :: search_datai :: SearchData4 [14:12] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData4_MASK          0x0000000000007000
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData4_SHIFT         12

/* FPM_SEARCH_FPM :: search_datai :: SearchData3 [11:09] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData3_MASK          0x0000000000000e00
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData3_SHIFT         9

/* FPM_SEARCH_FPM :: search_datai :: SearchData2 [08:06] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData2_MASK          0x00000000000001c0
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData2_SHIFT         6

/* FPM_SEARCH_FPM :: search_datai :: SearchData1 [05:03] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData1_MASK          0x0000000000000038
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData1_SHIFT         3

/* FPM_SEARCH_FPM :: search_datai :: SearchData0 [02:00] */
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData0_MASK          0x0000000000000007
#define BCHP_FPM_SEARCH_FPM_search_datai_SearchData0_SHIFT         0


#endif /* #ifndef BCHP_FPM_SEARCH_FPM_H__ */

/* End of File */
