/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Mar  3 03:33:07 2015
 *                 Full Compile MD5 Checksum  b5f19c74ab37a2906e9421a8b2559715
 *                     (minus title and desc)
 *                 MD5 Checksum               778db12b311d8f0cfe2c790ec2a4bd84
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_MIB0_H__
#define BCHP_MIB0_H__

/***************************************************************************
 *MIB0 - MIB Registers
 ***************************************************************************/
#define BCHP_MIB0_GRFCS                          0x12c00c00 /* [RW] Receive FCS Error Counter */
#define BCHP_MIB0_GRXCF                          0x12c00c04 /* [RW] Receive Control Frame Packet Counter */
#define BCHP_MIB0_GRXPF                          0x12c00c08 /* [RW] Receive Pause Frame Packet Counter */
#define BCHP_MIB0_GRXUO                          0x12c00c0c /* [RW] Receive Unknown OP Code Packet Counter */
#define BCHP_MIB0_GRALN                          0x12c00c10 /* [RW] Receive Alignmenet Error Counter */
#define BCHP_MIB0_GRFLR                          0x12c00c14 /* [RW] Receive Frame Length Out Of Range Counter */
#define BCHP_MIB0_GRCDE                          0x12c00c18 /* [RW] Receive Code Error Packet Counter */
#define BCHP_MIB0_GRFCR                          0x12c00c1c /* [RW] Receive Carrier Sense Error Packet Counter */
#define BCHP_MIB0_GROVR                          0x12c00c20 /* [RW] Receive Oversize Packet Counter */
#define BCHP_MIB0_GRJBR                          0x12c00c24 /* [RW] Receive Jabber Counter */
#define BCHP_MIB0_GRMTUE                         0x12c00c28 /* [RW] Receive MTU Error Packet Counter */
#define BCHP_MIB0_RRPKT                          0x12c00c2c /* [RW] Receive RUNT Packet Counter */
#define BCHP_MIB0_RRUND                          0x12c00c30 /* [RW] Receive RUNT Packet And Contain A Valid FCS */
#define BCHP_MIB0_RRFRG                          0x12c00c34 /* [RW] Receive RUNT Packet And Contain Invalid FCS or Alignment Error */
#define BCHP_MIB0_RRBYT                          0x12c00c38 /* [RW] Receive RUNT Packet Byte Counter */
#define BCHP_MIB0_GRMCA                          0x12c00c3c /* [RW] Receive Multicast Frame Counter */
#define BCHP_MIB0_GRBCA                          0x12c00c40 /* [RW] Receive Broadcast Frame Counter */
#define BCHP_MIB0_GR64                           0x12c00c44 /* [RW] Receive 64B Frame Counter */
#define BCHP_MIB0_GR127                          0x12c00c48 /* [RW] Receive 65B to 127B Frame Counter */
#define BCHP_MIB0_GR255                          0x12c00c4c /* [RW] Receive 128B to 255B Frame Counter */
#define BCHP_MIB0_GR511                          0x12c00c50 /* [RW] Receive 256B to 511B Frame Counter */
#define BCHP_MIB0_GR1023                         0x12c00c54 /* [RW] Receive 512B to 1023B Frame Counter */
#define BCHP_MIB0_GR1518                         0x12c00c58 /* [RW] Receive 1024B to 1518B Frame Counter */
#define BCHP_MIB0_GRMGV                          0x12c00c5c /* [RW] Receive 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB0_GR2047                         0x12c00c60 /* [RW] Receive 1522B to 2047B Frame Counter */
#define BCHP_MIB0_GR4095                         0x12c00c64 /* [RW] Receive 2048B to 4095B Frame Counter */
#define BCHP_MIB0_GR9216                         0x12c00c68 /* [RW] Receive 4096B to 9216B Frame Counter */
#define BCHP_MIB0_GRPKT                          0x12c00c6c /* [RW] Receive Packet Counter */
#define BCHP_MIB0_GRBYT                          0x12c00c70 /* [RW] Receive Byte Counter */
#define BCHP_MIB0_GRUC                           0x12c00c74 /* [RW] Receive Unicast Packet Counter */
#define BCHP_MIB0_GRPOK                          0x12c00c78 /* [RW] Receive Good Packet Counter */
#define BCHP_MIB0_GRPPP                          0x12c00c7c /* [RW] Receive PPP Packet Counter */
#define BCHP_MIB0_GRCRC                          0x12c00c80 /* [RW] Receive CRC Match Packet Counter */
#define BCHP_MIB0_GTXPF                          0x12c00c84 /* [RW] Transmit Pause Frame Packet Counter */
#define BCHP_MIB0_GTJBR                          0x12c00c88 /* [RW] Transmit Jabber Counter */
#define BCHP_MIB0_GTFCS                          0x12c00c8c /* [RW] Transmit FCS Error Counter */
#define BCHP_MIB0_GTXCF                          0x12c00c90 /* [RW] Transmit Control Frame Packet Counter */
#define BCHP_MIB0_GTOVR                          0x12c00c94 /* [RW] Transmit Oversize Packet Counter */
#define BCHP_MIB0_GTDRF                          0x12c00c98 /* [RW] Transmit Deferral Packet Counter */
#define BCHP_MIB0_GTEDF                          0x12c00c9c /* [RW] Transmit Excessive Deferral Packet Counter */
#define BCHP_MIB0_GTSCL                          0x12c00ca0 /* [RW] Transmit Single Collision Packet Counter */
#define BCHP_MIB0_GTMCL                          0x12c00ca4 /* [RW] Transmit Multiple Collision Packet Counter */
#define BCHP_MIB0_GTLCL                          0x12c00ca8 /* [RW] Transmit Late Collision Packet Counter */
#define BCHP_MIB0_GTXCL                          0x12c00cac /* [RW] Transmit Excessive Collision Packet Counter */
#define BCHP_MIB0_GTFRG                          0x12c00cb0 /* [RW] Transmit Fragments Packet Counter */
#define BCHP_MIB0_GTNCL                          0x12c00cb4 /* [RW] Transmit Total Collision Counter */
#define BCHP_MIB0_GTMCA                          0x12c00cb8 /* [RW] Transmit Multicast Packet Counter */
#define BCHP_MIB0_GTBCA                          0x12c00cbc /* [RW] Transmit Broadcast Packet Counter */
#define BCHP_MIB0_TR64                           0x12c00cc0 /* [RW] Transmit 64B Frame Counter */
#define BCHP_MIB0_TR127                          0x12c00cc4 /* [RW] Transmit 65B to 127B Frame Counter */
#define BCHP_MIB0_TR255                          0x12c00cc8 /* [RW] Transmit 128B to 255B Frame Counter */
#define BCHP_MIB0_TR511                          0x12c00ccc /* [RW] Transmit 256B to 511B Frame Counter */
#define BCHP_MIB0_TR1023                         0x12c00cd0 /* [RW] Transmit 512B to 1023B Frame Counter */
#define BCHP_MIB0_TR1518                         0x12c00cd4 /* [RW] Transmit 1024B to 1518B Frame Counter */
#define BCHP_MIB0_TRMGV                          0x12c00cd8 /* [RW] Transmit 1519B to 1522B Good VLAN Frame Counter */
#define BCHP_MIB0_TR2047                         0x12c00cdc /* [RW] Transmit 1522B to 2047B Frame Counter */
#define BCHP_MIB0_TR4095                         0x12c00ce0 /* [RW] Transmit 2048B to 4095B Frame Counter */
#define BCHP_MIB0_TR9216                         0x12c00ce4 /* [RW] Transmit 4096B to 9216B Frame Counter */
#define BCHP_MIB0_GTPKT                          0x12c00ce8 /* [RW] Transmit Packet Counter */
#define BCHP_MIB0_GTBYT                          0x12c00cec /* [RW] Transmit Byte Counter */
#define BCHP_MIB0_GTUC                           0x12c00cf0 /* [RW] Transmit Unicast Packet Counter */
#define BCHP_MIB0_GTPOK                          0x12c00cf4 /* [RW] Transmit Good Packet Counter */

/***************************************************************************
 *GRFCS - Receive FCS Error Counter
 ***************************************************************************/
/* MIB0 :: GRFCS :: RO [31:00] */
#define BCHP_MIB0_GRFCS_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRFCS_RO_SHIFT                                   0

/***************************************************************************
 *GRXCF - Receive Control Frame Packet Counter
 ***************************************************************************/
/* MIB0 :: GRXCF :: RO [31:00] */
#define BCHP_MIB0_GRXCF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRXCF_RO_SHIFT                                   0

/***************************************************************************
 *GRXPF - Receive Pause Frame Packet Counter
 ***************************************************************************/
/* MIB0 :: GRXPF :: RO [31:00] */
#define BCHP_MIB0_GRXPF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRXPF_RO_SHIFT                                   0

/***************************************************************************
 *GRXUO - Receive Unknown OP Code Packet Counter
 ***************************************************************************/
/* MIB0 :: GRXUO :: RO [31:00] */
#define BCHP_MIB0_GRXUO_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRXUO_RO_SHIFT                                   0

/***************************************************************************
 *GRALN - Receive Alignmenet Error Counter
 ***************************************************************************/
/* MIB0 :: GRALN :: RO [31:00] */
#define BCHP_MIB0_GRALN_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRALN_RO_SHIFT                                   0

/***************************************************************************
 *GRFLR - Receive Frame Length Out Of Range Counter
 ***************************************************************************/
/* MIB0 :: GRFLR :: RO [31:00] */
#define BCHP_MIB0_GRFLR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRFLR_RO_SHIFT                                   0

/***************************************************************************
 *GRCDE - Receive Code Error Packet Counter
 ***************************************************************************/
/* MIB0 :: GRCDE :: RO [31:00] */
#define BCHP_MIB0_GRCDE_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRCDE_RO_SHIFT                                   0

/***************************************************************************
 *GRFCR - Receive Carrier Sense Error Packet Counter
 ***************************************************************************/
/* MIB0 :: GRFCR :: RO [31:00] */
#define BCHP_MIB0_GRFCR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRFCR_RO_SHIFT                                   0

/***************************************************************************
 *GROVR - Receive Oversize Packet Counter
 ***************************************************************************/
/* MIB0 :: GROVR :: RO [31:00] */
#define BCHP_MIB0_GROVR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GROVR_RO_SHIFT                                   0

/***************************************************************************
 *GRJBR - Receive Jabber Counter
 ***************************************************************************/
/* MIB0 :: GRJBR :: RO [31:00] */
#define BCHP_MIB0_GRJBR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRJBR_RO_SHIFT                                   0

/***************************************************************************
 *GRMTUE - Receive MTU Error Packet Counter
 ***************************************************************************/
/* MIB0 :: GRMTUE :: RO [31:00] */
#define BCHP_MIB0_GRMTUE_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GRMTUE_RO_SHIFT                                  0

/***************************************************************************
 *RRPKT - Receive RUNT Packet Counter
 ***************************************************************************/
/* MIB0 :: RRPKT :: RO [31:00] */
#define BCHP_MIB0_RRPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_RRPKT_RO_SHIFT                                   0

/***************************************************************************
 *RRUND - Receive RUNT Packet And Contain A Valid FCS
 ***************************************************************************/
/* MIB0 :: RRUND :: RO [31:00] */
#define BCHP_MIB0_RRUND_RO_MASK                                    0xffffffff
#define BCHP_MIB0_RRUND_RO_SHIFT                                   0

/***************************************************************************
 *RRFRG - Receive RUNT Packet And Contain Invalid FCS or Alignment Error
 ***************************************************************************/
/* MIB0 :: RRFRG :: RO [31:00] */
#define BCHP_MIB0_RRFRG_RO_MASK                                    0xffffffff
#define BCHP_MIB0_RRFRG_RO_SHIFT                                   0

/***************************************************************************
 *RRBYT - Receive RUNT Packet Byte Counter
 ***************************************************************************/
/* MIB0 :: RRBYT :: RO [31:00] */
#define BCHP_MIB0_RRBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_RRBYT_RO_SHIFT                                   0

/***************************************************************************
 *GRMCA - Receive Multicast Frame Counter
 ***************************************************************************/
/* MIB0 :: GRMCA :: RO [31:00] */
#define BCHP_MIB0_GRMCA_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRMCA_RO_SHIFT                                   0

/***************************************************************************
 *GRBCA - Receive Broadcast Frame Counter
 ***************************************************************************/
/* MIB0 :: GRBCA :: RO [31:00] */
#define BCHP_MIB0_GRBCA_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRBCA_RO_SHIFT                                   0

/***************************************************************************
 *GR64 - Receive 64B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR64 :: RO [31:00] */
#define BCHP_MIB0_GR64_RO_MASK                                     0xffffffff
#define BCHP_MIB0_GR64_RO_SHIFT                                    0

/***************************************************************************
 *GR127 - Receive 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR127 :: RO [31:00] */
#define BCHP_MIB0_GR127_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GR127_RO_SHIFT                                   0

/***************************************************************************
 *GR255 - Receive 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR255 :: RO [31:00] */
#define BCHP_MIB0_GR255_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GR255_RO_SHIFT                                   0

/***************************************************************************
 *GR511 - Receive 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR511 :: RO [31:00] */
#define BCHP_MIB0_GR511_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GR511_RO_SHIFT                                   0

/***************************************************************************
 *GR1023 - Receive 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR1023 :: RO [31:00] */
#define BCHP_MIB0_GR1023_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GR1023_RO_SHIFT                                  0

/***************************************************************************
 *GR1518 - Receive 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR1518 :: RO [31:00] */
#define BCHP_MIB0_GR1518_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GR1518_RO_SHIFT                                  0

/***************************************************************************
 *GRMGV - Receive 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB0 :: GRMGV :: RO [31:00] */
#define BCHP_MIB0_GRMGV_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRMGV_RO_SHIFT                                   0

/***************************************************************************
 *GR2047 - Receive 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR2047 :: RO [31:00] */
#define BCHP_MIB0_GR2047_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GR2047_RO_SHIFT                                  0

/***************************************************************************
 *GR4095 - Receive 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR4095 :: RO [31:00] */
#define BCHP_MIB0_GR4095_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GR4095_RO_SHIFT                                  0

/***************************************************************************
 *GR9216 - Receive 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB0 :: GR9216 :: RO [31:00] */
#define BCHP_MIB0_GR9216_RO_MASK                                   0xffffffff
#define BCHP_MIB0_GR9216_RO_SHIFT                                  0

/***************************************************************************
 *GRPKT - Receive Packet Counter
 ***************************************************************************/
/* MIB0 :: GRPKT :: RO [31:00] */
#define BCHP_MIB0_GRPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRPKT_RO_SHIFT                                   0

/***************************************************************************
 *GRBYT - Receive Byte Counter
 ***************************************************************************/
/* MIB0 :: GRBYT :: RO [31:00] */
#define BCHP_MIB0_GRBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRBYT_RO_SHIFT                                   0

/***************************************************************************
 *GRUC - Receive Unicast Packet Counter
 ***************************************************************************/
/* MIB0 :: GRUC :: RO [31:00] */
#define BCHP_MIB0_GRUC_RO_MASK                                     0xffffffff
#define BCHP_MIB0_GRUC_RO_SHIFT                                    0

/***************************************************************************
 *GRPOK - Receive Good Packet Counter
 ***************************************************************************/
/* MIB0 :: GRPOK :: RO [31:00] */
#define BCHP_MIB0_GRPOK_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRPOK_RO_SHIFT                                   0

/***************************************************************************
 *GRPPP - Receive PPP Packet Counter
 ***************************************************************************/
/* MIB0 :: GRPPP :: RO [31:00] */
#define BCHP_MIB0_GRPPP_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRPPP_RO_SHIFT                                   0

/***************************************************************************
 *GRCRC - Receive CRC Match Packet Counter
 ***************************************************************************/
/* MIB0 :: GRCRC :: RO [31:00] */
#define BCHP_MIB0_GRCRC_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GRCRC_RO_SHIFT                                   0

/***************************************************************************
 *GTXPF - Transmit Pause Frame Packet Counter
 ***************************************************************************/
/* MIB0 :: GTXPF :: RO [31:00] */
#define BCHP_MIB0_GTXPF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTXPF_RO_SHIFT                                   0

/***************************************************************************
 *GTJBR - Transmit Jabber Counter
 ***************************************************************************/
/* MIB0 :: GTJBR :: RO [31:00] */
#define BCHP_MIB0_GTJBR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTJBR_RO_SHIFT                                   0

/***************************************************************************
 *GTFCS - Transmit FCS Error Counter
 ***************************************************************************/
/* MIB0 :: GTFCS :: RO [31:00] */
#define BCHP_MIB0_GTFCS_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTFCS_RO_SHIFT                                   0

/***************************************************************************
 *GTXCF - Transmit Control Frame Packet Counter
 ***************************************************************************/
/* MIB0 :: GTXCF :: RO [31:00] */
#define BCHP_MIB0_GTXCF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTXCF_RO_SHIFT                                   0

/***************************************************************************
 *GTOVR - Transmit Oversize Packet Counter
 ***************************************************************************/
/* MIB0 :: GTOVR :: RO [31:00] */
#define BCHP_MIB0_GTOVR_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTOVR_RO_SHIFT                                   0

/***************************************************************************
 *GTDRF - Transmit Deferral Packet Counter
 ***************************************************************************/
/* MIB0 :: GTDRF :: RO [31:00] */
#define BCHP_MIB0_GTDRF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTDRF_RO_SHIFT                                   0

/***************************************************************************
 *GTEDF - Transmit Excessive Deferral Packet Counter
 ***************************************************************************/
/* MIB0 :: GTEDF :: RO [31:00] */
#define BCHP_MIB0_GTEDF_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTEDF_RO_SHIFT                                   0

/***************************************************************************
 *GTSCL - Transmit Single Collision Packet Counter
 ***************************************************************************/
/* MIB0 :: GTSCL :: RO [31:00] */
#define BCHP_MIB0_GTSCL_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTSCL_RO_SHIFT                                   0

/***************************************************************************
 *GTMCL - Transmit Multiple Collision Packet Counter
 ***************************************************************************/
/* MIB0 :: GTMCL :: RO [31:00] */
#define BCHP_MIB0_GTMCL_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTMCL_RO_SHIFT                                   0

/***************************************************************************
 *GTLCL - Transmit Late Collision Packet Counter
 ***************************************************************************/
/* MIB0 :: GTLCL :: RO [31:00] */
#define BCHP_MIB0_GTLCL_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTLCL_RO_SHIFT                                   0

/***************************************************************************
 *GTXCL - Transmit Excessive Collision Packet Counter
 ***************************************************************************/
/* MIB0 :: GTXCL :: RO [31:00] */
#define BCHP_MIB0_GTXCL_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTXCL_RO_SHIFT                                   0

/***************************************************************************
 *GTFRG - Transmit Fragments Packet Counter
 ***************************************************************************/
/* MIB0 :: GTFRG :: RO [31:00] */
#define BCHP_MIB0_GTFRG_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTFRG_RO_SHIFT                                   0

/***************************************************************************
 *GTNCL - Transmit Total Collision Counter
 ***************************************************************************/
/* MIB0 :: GTNCL :: RO [31:00] */
#define BCHP_MIB0_GTNCL_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTNCL_RO_SHIFT                                   0

/***************************************************************************
 *GTMCA - Transmit Multicast Packet Counter
 ***************************************************************************/
/* MIB0 :: GTMCA :: RO [31:00] */
#define BCHP_MIB0_GTMCA_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTMCA_RO_SHIFT                                   0

/***************************************************************************
 *GTBCA - Transmit Broadcast Packet Counter
 ***************************************************************************/
/* MIB0 :: GTBCA :: RO [31:00] */
#define BCHP_MIB0_GTBCA_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTBCA_RO_SHIFT                                   0

/***************************************************************************
 *TR64 - Transmit 64B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR64 :: RO [31:00] */
#define BCHP_MIB0_TR64_RO_MASK                                     0xffffffff
#define BCHP_MIB0_TR64_RO_SHIFT                                    0

/***************************************************************************
 *TR127 - Transmit 65B to 127B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR127 :: RO [31:00] */
#define BCHP_MIB0_TR127_RO_MASK                                    0xffffffff
#define BCHP_MIB0_TR127_RO_SHIFT                                   0

/***************************************************************************
 *TR255 - Transmit 128B to 255B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR255 :: RO [31:00] */
#define BCHP_MIB0_TR255_RO_MASK                                    0xffffffff
#define BCHP_MIB0_TR255_RO_SHIFT                                   0

/***************************************************************************
 *TR511 - Transmit 256B to 511B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR511 :: RO [31:00] */
#define BCHP_MIB0_TR511_RO_MASK                                    0xffffffff
#define BCHP_MIB0_TR511_RO_SHIFT                                   0

/***************************************************************************
 *TR1023 - Transmit 512B to 1023B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR1023 :: RO [31:00] */
#define BCHP_MIB0_TR1023_RO_MASK                                   0xffffffff
#define BCHP_MIB0_TR1023_RO_SHIFT                                  0

/***************************************************************************
 *TR1518 - Transmit 1024B to 1518B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR1518 :: RO [31:00] */
#define BCHP_MIB0_TR1518_RO_MASK                                   0xffffffff
#define BCHP_MIB0_TR1518_RO_SHIFT                                  0

/***************************************************************************
 *TRMGV - Transmit 1519B to 1522B Good VLAN Frame Counter
 ***************************************************************************/
/* MIB0 :: TRMGV :: RO [31:00] */
#define BCHP_MIB0_TRMGV_RO_MASK                                    0xffffffff
#define BCHP_MIB0_TRMGV_RO_SHIFT                                   0

/***************************************************************************
 *TR2047 - Transmit 1522B to 2047B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR2047 :: RO [31:00] */
#define BCHP_MIB0_TR2047_RO_MASK                                   0xffffffff
#define BCHP_MIB0_TR2047_RO_SHIFT                                  0

/***************************************************************************
 *TR4095 - Transmit 2048B to 4095B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR4095 :: RO [31:00] */
#define BCHP_MIB0_TR4095_RO_MASK                                   0xffffffff
#define BCHP_MIB0_TR4095_RO_SHIFT                                  0

/***************************************************************************
 *TR9216 - Transmit 4096B to 9216B Frame Counter
 ***************************************************************************/
/* MIB0 :: TR9216 :: RO [31:00] */
#define BCHP_MIB0_TR9216_RO_MASK                                   0xffffffff
#define BCHP_MIB0_TR9216_RO_SHIFT                                  0

/***************************************************************************
 *GTPKT - Transmit Packet Counter
 ***************************************************************************/
/* MIB0 :: GTPKT :: RO [31:00] */
#define BCHP_MIB0_GTPKT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTPKT_RO_SHIFT                                   0

/***************************************************************************
 *GTBYT - Transmit Byte Counter
 ***************************************************************************/
/* MIB0 :: GTBYT :: RO [31:00] */
#define BCHP_MIB0_GTBYT_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTBYT_RO_SHIFT                                   0

/***************************************************************************
 *GTUC - Transmit Unicast Packet Counter
 ***************************************************************************/
/* MIB0 :: GTUC :: RO [31:00] */
#define BCHP_MIB0_GTUC_RO_MASK                                     0xffffffff
#define BCHP_MIB0_GTUC_RO_SHIFT                                    0

/***************************************************************************
 *GTPOK - Transmit Good Packet Counter
 ***************************************************************************/
/* MIB0 :: GTPOK :: RO [31:00] */
#define BCHP_MIB0_GTPOK_RO_MASK                                    0xffffffff
#define BCHP_MIB0_GTPOK_RO_SHIFT                                   0

#endif /* #ifndef BCHP_MIB0_H__ */

/* End of File */
