/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Mar  3 03:33:05 2015
 *                 Full Compile MD5 Checksum  b5f19c74ab37a2906e9421a8b2559715
 *                     (minus title and desc)
 *                 MD5 Checksum               778db12b311d8f0cfe2c790ec2a4bd84
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_UNIMAC_CORE1_H__
#define BCHP_UNIMAC_CORE1_H__

/***************************************************************************
 *UNIMAC_CORE1 - Unimac Core Registers
 ***************************************************************************/
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL     0x12c02804 /* [RW] UniMAC Half Duplex Backpressure Control Register */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD             0x12c02808 /* [RW] UniMAC Command Register */
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC0            0x12c0280c /* [RW] UniMAC MAC 0 */
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1            0x12c02810 /* [RW] UniMAC MAC 1 */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN         0x12c02814 /* [RW] UniMAC Frame Length */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT     0x12c02818 /* [RW] UniMAC Pause Quanta */
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET      0x12c02840 /* [RW] UniMAC EFM Preamble Length */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE            0x12c02844 /* [RO] UniMAC Mode */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0        0x12c02848 /* [RW] UniMAC Preamble Outer TAG 0 */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1        0x12c0284c /* [RW] UniMAC Preamble Outer TAG 1 */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN      0x12c0285c /* [RW] UniMAC Inter Packet Gap */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_PROG_TX_CRC 0x12c02b10 /* [RW] UniMAC Programmable CRC value */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL    0x12c02b14 /* [RW] UniMAC Misc. MACSEC Control Register */
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL 0x12c02b18 /* [RO] UniMAC Timestamp Status */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_TS_DATA      0x12c02b1c /* [RO] UniMAC Timestamp Data */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL     0x12c02b30 /* [RW] UniMAC Repetitive Pause Control in TX direction */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH    0x12c02b34 /* [RW] UniMAC TX Flush */
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT     0x12c02b38 /* [RO] UniMAC RX FIFO Status */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT     0x12c02b3c /* [RO] UniMAC TX FIFO Status */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL       0x12c02b40 /* [RW] UniMAC PPP Control */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL 0x12c02b44 /* [RW] UniMAC Refresh Control */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL0  0x12c02b48 /* [RW] UniMAC TX Pause PRBL[31:0] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL1  0x12c02b4c /* [RW] UniMAC TX Pause PRBL[63:32] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL2  0x12c02b50 /* [RW] UniMAC TX Pause PRBL[95:64] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL3  0x12c02b54 /* [RW] UniMAC TX Pause PRBL[127:96] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL0  0x12c02b58 /* [RO] UniMAC RX Pause PRBL[31:0] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL1  0x12c02b5c /* [RO] UniMAC RX Pause PRBL[63:32] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL2  0x12c02b60 /* [RO] UniMAC RX Pause PRBL[95:64] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL3  0x12c02b64 /* [RO] UniMAC RX Pause PRBL[127:96] */

/***************************************************************************
 *UNIMAC_HD_BKP_CNTL - UniMAC Half Duplex Backpressure Control Register
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_HD_BKP_CNTL :: reserved0 [31:07] */
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_reserved0_MASK        0xffffff80
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_reserved0_SHIFT       7

/* UNIMAC_CORE1 :: UNIMAC_HD_BKP_CNTL :: ipg_config_rx [06:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_ipg_config_rx_MASK    0x0000007c
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_ipg_config_rx_SHIFT   2
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_ipg_config_rx_DEFAULT 0x00000005

/* UNIMAC_CORE1 :: UNIMAC_HD_BKP_CNTL :: hd_fc_bkoff_ok [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_bkoff_ok_MASK   0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_bkoff_ok_SHIFT  1
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_bkoff_ok_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_HD_BKP_CNTL :: hd_fc_ena [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_ena_MASK        0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_ena_SHIFT       0
#define BCHP_UNIMAC_CORE1_UNIMAC_HD_BKP_CNTL_hd_fc_ena_DEFAULT     0x00000000

/***************************************************************************
 *UNIMAC_CMD - UniMAC Command Register
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_CMD :: reserved0 [31:31] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved0_MASK                0x80000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved0_SHIFT               31

/* UNIMAC_CORE1 :: UNIMAC_CMD :: runt_filter_dis [30:30] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_runt_filter_dis_MASK          0x40000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_runt_filter_dis_SHIFT         30
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_runt_filter_dis_DEFAULT       0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: txrx_en_config [29:29] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_txrx_en_config_MASK           0x20000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_txrx_en_config_SHIFT          29
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_txrx_en_config_DEFAULT        0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: tx_pause_ignore [28:28] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_pause_ignore_MASK          0x10000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_pause_ignore_SHIFT         28
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_pause_ignore_DEFAULT       0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: prbl_ena [27:27] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_prbl_ena_MASK                 0x08000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_prbl_ena_SHIFT                27
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_prbl_ena_DEFAULT              0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: rx_err_disc [26:26] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_err_disc_MASK              0x04000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_err_disc_SHIFT             26
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_err_disc_DEFAULT           0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: rmt_loop_ena [25:25] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rmt_loop_ena_MASK             0x02000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rmt_loop_ena_SHIFT            25
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rmt_loop_ena_DEFAULT          0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: no_lgth_check [24:24] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_no_lgth_check_MASK            0x01000000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_no_lgth_check_SHIFT           24
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_no_lgth_check_DEFAULT         0x00000001

/* UNIMAC_CORE1 :: UNIMAC_CMD :: cntl_frm_ena [23:23] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_cntl_frm_ena_MASK             0x00800000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_cntl_frm_ena_SHIFT            23
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_cntl_frm_ena_DEFAULT          0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: ena_ext_config [22:22] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_ena_ext_config_MASK           0x00400000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_ena_ext_config_SHIFT          22
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_ena_ext_config_DEFAULT        0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: reserved1 [21:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved1_MASK                0x003f0000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved1_SHIFT               16

/* UNIMAC_CORE1 :: UNIMAC_CMD :: lcl_loop_ena [15:15] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_lcl_loop_ena_MASK             0x00008000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_lcl_loop_ena_SHIFT            15
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_lcl_loop_ena_DEFAULT          0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: reserved2 [14:14] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved2_MASK                0x00004000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved2_SHIFT               14

/* UNIMAC_CORE1 :: UNIMAC_CMD :: sw_reset [13:13] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_sw_reset_MASK                 0x00002000
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_sw_reset_SHIFT                13
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_sw_reset_DEFAULT              0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: reserved3 [12:11] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved3_MASK                0x00001800
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_reserved3_SHIFT               11

/* UNIMAC_CORE1 :: UNIMAC_CMD :: hd_ena [10:10] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_hd_ena_MASK                   0x00000400
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_hd_ena_SHIFT                  10
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_hd_ena_DEFAULT                0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: tx_addr_ins [09:09] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_addr_ins_MASK              0x00000200
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_addr_ins_SHIFT             9
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_addr_ins_DEFAULT           0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: rx_pause_ignore [08:08] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_pause_ignore_MASK          0x00000100
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_pause_ignore_SHIFT         8
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_pause_ignore_DEFAULT       0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: pause_fwd [07:07] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pause_fwd_MASK                0x00000080
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pause_fwd_SHIFT               7
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pause_fwd_DEFAULT             0x00000001

/* UNIMAC_CORE1 :: UNIMAC_CMD :: crc_fwd [06:06] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_crc_fwd_MASK                  0x00000040
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_crc_fwd_SHIFT                 6
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_crc_fwd_DEFAULT               0x00000001

/* UNIMAC_CORE1 :: UNIMAC_CMD :: pad_en [05:05] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pad_en_MASK                   0x00000020
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pad_en_SHIFT                  5
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_pad_en_DEFAULT                0x00000000

/* UNIMAC_CORE1 :: UNIMAC_CMD :: promis_en [04:04] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_promis_en_MASK                0x00000010
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_promis_en_SHIFT               4
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_promis_en_DEFAULT             0x00000001

/* UNIMAC_CORE1 :: UNIMAC_CMD :: eth_speed [03:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_eth_speed_MASK                0x0000000c
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_eth_speed_SHIFT               2
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_eth_speed_DEFAULT             0x00000002

/* UNIMAC_CORE1 :: UNIMAC_CMD :: rx_ena [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_ena_MASK                   0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_ena_SHIFT                  1
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_rx_ena_DEFAULT                0x00000001

/* UNIMAC_CORE1 :: UNIMAC_CMD :: tx_ena [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_ena_MASK                   0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_ena_SHIFT                  0
#define BCHP_UNIMAC_CORE1_UNIMAC_CMD_tx_ena_DEFAULT                0x00000001

/***************************************************************************
 *UNIMAC_MAC0 - UniMAC MAC 0
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_MAC0 :: mac_0 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC0_mac_0_MASK                   0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC0_mac_0_SHIFT                  0
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC0_mac_0_DEFAULT                0x00000000

/***************************************************************************
 *UNIMAC_MAC1 - UniMAC MAC 1
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_MAC1 :: reserved0 [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1_reserved0_MASK               0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1_reserved0_SHIFT              16

/* UNIMAC_CORE1 :: UNIMAC_MAC1 :: mac_1 [15:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1_mac_1_MASK                   0x0000ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1_mac_1_SHIFT                  0
#define BCHP_UNIMAC_CORE1_UNIMAC_MAC1_mac_1_DEFAULT                0x00000000

/***************************************************************************
 *UNIMAC_FRM_LEN - UniMAC Frame Length
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_FRM_LEN :: reserved0 [31:14] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN_reserved0_MASK            0xffffc000
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN_reserved0_SHIFT           14

/* UNIMAC_CORE1 :: UNIMAC_FRM_LEN :: frame_length [13:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN_frame_length_MASK         0x00003fff
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN_frame_length_SHIFT        0
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_LEN_frame_length_DEFAULT      0x000005ee

/***************************************************************************
 *UNIMAC_PAUSE_QUNAT - UniMAC Pause Quanta
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_PAUSE_QUNAT :: reserved0 [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT_reserved0_MASK        0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT_reserved0_SHIFT       16

/* UNIMAC_CORE1 :: UNIMAC_PAUSE_QUNAT :: pause_quant [15:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT_pause_quant_MASK      0x0000ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT_pause_quant_SHIFT     0
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_QUNAT_pause_quant_DEFAULT   0x0000ffff

/***************************************************************************
 *UNIMAC_SFD_OFFSET - UniMAC EFM Preamble Length
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_SFD_OFFSET :: reserved0 [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET_reserved0_MASK         0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET_reserved0_SHIFT        16

/* UNIMAC_CORE1 :: UNIMAC_SFD_OFFSET :: sdf_offset [15:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET_sdf_offset_MASK        0x0000ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET_sdf_offset_SHIFT       0
#define BCHP_UNIMAC_CORE1_UNIMAC_SFD_OFFSET_sdf_offset_DEFAULT     0x00000000

/***************************************************************************
 *UNIMAC_MODE - UniMAC Mode
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_MODE :: reserved0 [31:06] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_reserved0_MASK               0xffffffc0
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_reserved0_SHIFT              6

/* UNIMAC_CORE1 :: UNIMAC_MODE :: mac_link_stat [05:05] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_link_stat_MASK           0x00000020
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_link_stat_SHIFT          5
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_link_stat_DEFAULT        0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MODE :: mac_tx_pause [04:04] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_tx_pause_MASK            0x00000010
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_tx_pause_SHIFT           4
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_tx_pause_DEFAULT         0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MODE :: mac_rx_pause [03:03] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_rx_pause_MASK            0x00000008
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_rx_pause_SHIFT           3
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_rx_pause_DEFAULT         0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MODE :: mac_duplex [02:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_duplex_MASK              0x00000004
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_duplex_SHIFT             2
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_duplex_DEFAULT           0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MODE :: mac_speed [01:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_speed_MASK               0x00000003
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_speed_SHIFT              0
#define BCHP_UNIMAC_CORE1_UNIMAC_MODE_mac_speed_DEFAULT            0x00000000

/***************************************************************************
 *UNIMAC_FRM_TAG0 - UniMAC Preamble Outer TAG 0
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_FRM_TAG0 :: reserved0 [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0_reserved0_MASK           0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0_reserved0_SHIFT          16

/* UNIMAC_CORE1 :: UNIMAC_FRM_TAG0 :: outer_tag [15:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0_outer_tag_MASK           0x0000ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0_outer_tag_SHIFT          0
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG0_outer_tag_DEFAULT        0x00008100

/***************************************************************************
 *UNIMAC_FRM_TAG1 - UniMAC Preamble Outer TAG 1
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_FRM_TAG1 :: reserved0 [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1_reserved0_MASK           0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1_reserved0_SHIFT          16

/* UNIMAC_CORE1 :: UNIMAC_FRM_TAG1 :: inner_tag [15:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1_inner_tag_MASK           0x0000ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1_inner_tag_SHIFT          0
#define BCHP_UNIMAC_CORE1_UNIMAC_FRM_TAG1_inner_tag_DEFAULT        0x00008100

/***************************************************************************
 *UNIMAC_TX_IPG_LEN - UniMAC Inter Packet Gap
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_IPG_LEN :: reserved0 [31:05] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN_reserved0_MASK         0xffffffe0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN_reserved0_SHIFT        5

/* UNIMAC_CORE1 :: UNIMAC_TX_IPG_LEN :: tx_ipg_len [04:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN_tx_ipg_len_MASK        0x0000001f
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN_tx_ipg_len_SHIFT       0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_IPG_LEN_tx_ipg_len_DEFAULT     0x00000000

/***************************************************************************
 *UNIMAC_MACSEC_PROG_TX_CRC - UniMAC Programmable CRC value
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_MACSEC_PROG_TX_CRC :: macsec_prog_tx_crc [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_PROG_TX_CRC_macsec_prog_tx_crc_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_PROG_TX_CRC_macsec_prog_tx_crc_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_PROG_TX_CRC_macsec_prog_tx_crc_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_MACSEC_CNTRL - UniMAC Misc. MACSEC Control Register
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_MACSEC_CNTRL :: reserved0 [31:03] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_reserved0_MASK       0xfffffff8
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_reserved0_SHIFT      3

/* UNIMAC_CORE1 :: UNIMAC_MACSEC_CNTRL :: tx_crc_program [02:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_program_MASK  0x00000004
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_program_SHIFT 2
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_program_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MACSEC_CNTRL :: tx_crc_corrupt_en [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_corrupt_en_MASK 0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_corrupt_en_SHIFT 1
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_crc_corrupt_en_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_MACSEC_CNTRL :: tx_lanuch_en [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_lanuch_en_MASK    0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_lanuch_en_SHIFT   0
#define BCHP_UNIMAC_CORE1_UNIMAC_MACSEC_CNTRL_tx_lanuch_en_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TS_STATUS_CNTRL - UniMAC Timestamp Status
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TS_STATUS_CNTRL :: reserved0 [31:04] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_reserved0_MASK    0xfffffff0
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_reserved0_SHIFT   4

/* UNIMAC_CORE1 :: UNIMAC_TS_STATUS_CNTRL :: word_avail [03:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_word_avail_MASK   0x0000000c
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_word_avail_SHIFT  2
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_word_avail_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_TS_STATUS_CNTRL :: tx_ts_fifo_empty [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_empty_MASK 0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_empty_SHIFT 1
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_empty_DEFAULT 0x00000001

/* UNIMAC_CORE1 :: UNIMAC_TS_STATUS_CNTRL :: tx_ts_fifo_full [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_full_MASK 0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_full_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TS_STATUS_CNTRL_tx_ts_fifo_full_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TX_TS_DATA - UniMAC Timestamp Data
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_TS_DATA :: tx_ts_data [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_TS_DATA_tx_ts_data_MASK        0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_TS_DATA_tx_ts_data_SHIFT       0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_TS_DATA_tx_ts_data_DEFAULT     0x00000000

/***************************************************************************
 *UNIMAC_PAUSE_CNTRL - UniMAC Repetitive Pause Control in TX direction
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_PAUSE_CNTRL :: reserved0 [31:18] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_reserved0_MASK        0xfffc0000
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_reserved0_SHIFT       18

/* UNIMAC_CORE1 :: UNIMAC_PAUSE_CNTRL :: pause_control_en [17:17] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_control_en_MASK 0x00020000
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_control_en_SHIFT 17
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_control_en_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_PAUSE_CNTRL :: pause_timer [16:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_timer_MASK      0x0001ffff
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_timer_SHIFT     0
#define BCHP_UNIMAC_CORE1_UNIMAC_PAUSE_CNTRL_pause_timer_DEFAULT   0x00000000

/***************************************************************************
 *UNIMAC_TXFIFO_FLUSH - UniMAC TX Flush
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TXFIFO_FLUSH :: reserved0 [31:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH_reserved0_MASK       0xfffffffe
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH_reserved0_SHIFT      1

/* UNIMAC_CORE1 :: UNIMAC_TXFIFO_FLUSH :: tx_flush [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH_tx_flush_MASK        0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH_tx_flush_SHIFT       0
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_FLUSH_tx_flush_DEFAULT     0x00000000

/***************************************************************************
 *UNIMAC_RXFIFO_STAT - UniMAC RX FIFO Status
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_RXFIFO_STAT :: reserved0 [31:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT_reserved0_MASK        0xfffffffc
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT_reserved0_SHIFT       2

/* UNIMAC_CORE1 :: UNIMAC_RXFIFO_STAT :: rxfifo_status [01:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT_rxfifo_status_MASK    0x00000003
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT_rxfifo_status_SHIFT   0
#define BCHP_UNIMAC_CORE1_UNIMAC_RXFIFO_STAT_rxfifo_status_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TXFIFO_STAT - UniMAC TX FIFO Status
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TXFIFO_STAT :: reserved0 [31:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_reserved0_MASK        0xfffffffc
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_reserved0_SHIFT       2

/* UNIMAC_CORE1 :: UNIMAC_TXFIFO_STAT :: txfifo_overrun [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_overrun_MASK   0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_overrun_SHIFT  1
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_overrun_DEFAULT 0x00000000

/* UNIMAC_CORE1 :: UNIMAC_TXFIFO_STAT :: txfifo_underrun [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_underrun_MASK  0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_underrun_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TXFIFO_STAT_txfifo_underrun_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_PPP_CNTRL - UniMAC PPP Control
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_PPP_CNTRL :: reserved0 [31:03] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_reserved0_MASK          0xfffffff8
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_reserved0_SHIFT         3

/* UNIMAC_CORE1 :: UNIMAC_PPP_CNTRL :: force_ppp_xon [02:02] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_force_ppp_xon_MASK      0x00000004
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_force_ppp_xon_SHIFT     2
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_force_ppp_xon_DEFAULT   0x00000000

/* UNIMAC_CORE1 :: UNIMAC_PPP_CNTRL :: ppp_en_rx [01:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_rx_MASK          0x00000002
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_rx_SHIFT         1
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_rx_DEFAULT       0x00000000

/* UNIMAC_CORE1 :: UNIMAC_PPP_CNTRL :: ppp_en_tx [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_tx_MASK          0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_tx_SHIFT         0
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_CNTRL_ppp_en_tx_DEFAULT       0x00000000

/***************************************************************************
 *UNIMAC_PPP_REFRESH_CNTRL - UniMAC Refresh Control
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_PPP_REFRESH_CNTRL :: ppp_refresh_timer [31:16] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_timer_MASK 0xffff0000
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_timer_SHIFT 16
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_timer_DEFAULT 0x00007fff

/* UNIMAC_CORE1 :: UNIMAC_PPP_REFRESH_CNTRL :: reserved0 [15:01] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_reserved0_MASK  0x0000fffe
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_reserved0_SHIFT 1

/* UNIMAC_CORE1 :: UNIMAC_PPP_REFRESH_CNTRL :: ppp_refresh_en [00:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_en_MASK 0x00000001
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_en_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_PPP_REFRESH_CNTRL_ppp_refresh_en_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TX_PAUSE_PREL0 - UniMAC TX Pause PRBL[31:0]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_PAUSE_PREL0 :: tx_pause_prb0 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL0_tx_pause_prb0_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL0_tx_pause_prb0_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL0_tx_pause_prb0_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TX_PAUSE_PREL1 - UniMAC TX Pause PRBL[63:32]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_PAUSE_PREL1 :: tx_pause_prb1 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL1_tx_pause_prb1_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL1_tx_pause_prb1_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL1_tx_pause_prb1_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TX_PAUSE_PREL2 - UniMAC TX Pause PRBL[95:64]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_PAUSE_PREL2 :: tx_pause_prb2 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL2_tx_pause_prb2_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL2_tx_pause_prb2_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL2_tx_pause_prb2_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_TX_PAUSE_PREL3 - UniMAC TX Pause PRBL[127:96]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_TX_PAUSE_PREL3 :: tx_pause_prb3 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL3_tx_pause_prb3_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL3_tx_pause_prb3_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_TX_PAUSE_PREL3_tx_pause_prb3_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_RX_PAUSE_PREL0 - UniMAC RX Pause PRBL[31:0]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_RX_PAUSE_PREL0 :: rx_pause_prb0 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL0_rx_pause_prb0_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL0_rx_pause_prb0_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL0_rx_pause_prb0_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_RX_PAUSE_PREL1 - UniMAC RX Pause PRBL[63:32]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_RX_PAUSE_PREL1 :: rx_pause_prb1 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL1_rx_pause_prb1_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL1_rx_pause_prb1_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL1_rx_pause_prb1_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_RX_PAUSE_PREL2 - UniMAC RX Pause PRBL[95:64]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_RX_PAUSE_PREL2 :: rx_pause_prb2 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL2_rx_pause_prb2_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL2_rx_pause_prb2_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL2_rx_pause_prb2_DEFAULT 0x00000000

/***************************************************************************
 *UNIMAC_RX_PAUSE_PREL3 - UniMAC RX Pause PRBL[127:96]
 ***************************************************************************/
/* UNIMAC_CORE1 :: UNIMAC_RX_PAUSE_PREL3 :: rx_pause_prb3 [31:00] */
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL3_rx_pause_prb3_MASK 0xffffffff
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL3_rx_pause_prb3_SHIFT 0
#define BCHP_UNIMAC_CORE1_UNIMAC_RX_PAUSE_PREL3_rx_pause_prb3_DEFAULT 0x00000000

#endif /* #ifndef BCHP_UNIMAC_CORE1_H__ */

/* End of File */
